import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.solutions': 'Solutions',
    'nav.projects': 'Projects',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    
    // Home Page
    'home.hero.title': 'Boost Your Business with Innovative Software Solutions',
    'home.hero.subtitle': 'We transform your challenges into digital opportunities. Experts in Openbravo, Odoo, Artificial Intelligence, and custom development for unprecedented efficiency.',
    'home.hero.viewServices': 'View Our Services',
    'home.hero.startProject': 'Start a Project',
    
    'home.valueProps.title': 'Your Strategic Partner in the Digital Era',
    'home.valueProps.subtitle': 'At Doce Leguas, we understand that each business is unique. We offer more than software development: we provide customized solutions that optimize processes, reduce costs, and open new growth avenues.',
    'home.valueProps.innovation': 'Constant Innovation',
    'home.valueProps.innovation.desc': 'Always at the forefront of the latest technologies.',
    'home.valueProps.custom': 'Custom Solutions',
    'home.valueProps.custom.desc': 'Developments that perfectly fit your needs.',
    'home.valueProps.results': 'Proven Results',
    'home.valueProps.results.desc': 'Real impact on your company\'s efficiency and profitability.',
    'home.valueProps.team': 'Expert Team',
    'home.valueProps.team.desc': 'Highly qualified and dedicated professionals.',
    
    'home.services.title': 'What Can We Do For You?',
    'home.services.subtitle': 'Explore our comprehensive range of services designed to transform your business operations.',
    'home.services.openbravo': 'Openbravo Development',
    'home.services.openbravo.desc': 'Maximize your ERP efficiency with our specialists.',
    'home.services.odoo': 'Odoo Implementation',
    'home.services.odoo.desc': 'Automate and centralize your business management.',
    'home.services.ai': 'AI Applications',
    'home.services.ai.desc': 'Transform data into strategic decisions and intelligent operations.',
    'home.services.custom': 'Custom Development',
    'home.services.custom.desc': 'Create the perfect tool for your unique challenges.',
    'home.services.n8n': 'N8n Workflows',
    'home.services.n8n.desc': 'Automate complex business processes with powerful workflow automation.',
    'home.services.automation': 'Business Automation',
    'home.services.automation.desc': 'Streamline operations and eliminate manual tasks with intelligent automation.',
    'home.services.learnMore': 'Learn More',
    
    'home.projects.title': 'Results That Speak for Themselves',
    'home.projects.subtitle': 'Discover how we\'ve helped companies achieve their digital transformation goals.',
    'home.projects.viewCase': 'View Case Study',
    
    'home.testimonials.title': 'What Our Clients Say',
    
    'home.cta.title': 'Ready to Take Your Business to the Next Level?',
    'home.cta.subtitle': 'Let us understand your challenges and offer you a solution that makes a difference. Contact us today for a no-obligation consultation.',
    'home.cta.schedule': 'Schedule a Meeting',
    'home.cta.contact': 'Contact Us Now',
    
    // Logistics & Retail Section
    'home.logistics.title': 'Specialized Solutions for Logistics & Retail',
    'home.logistics.subtitle': 'Transform your supply chain and retail operations with our industry-specific expertise and cutting-edge technology solutions.',
    'home.logistics.supply.title': 'Supply Chain Optimization',
    'home.logistics.supply.desc': 'Streamline your logistics operations with intelligent inventory management and automated workflows.',
    'home.logistics.supply.feature1': 'Real-time inventory tracking',
    'home.logistics.supply.feature2': 'Automated reordering systems',
    'home.logistics.supply.feature3': 'Predictive demand planning',
    'home.logistics.retail.title': 'Retail Management Systems',
    'home.logistics.retail.desc': 'Enhance customer experience and boost sales with integrated retail solutions.',
    'home.logistics.retail.feature1': 'Multi-channel POS systems',
    'home.logistics.retail.feature2': 'Customer loyalty programs',
    'home.logistics.retail.feature3': 'Sales analytics & reporting',
    'home.logistics.expertise.title': 'Industry Expertise',
    'home.logistics.expertise.desc': 'Years of experience delivering successful projects in logistics and retail sectors.',
    'home.logistics.expertise.stat1': 'Projects Delivered',
    'home.logistics.expertise.stat2': 'Client Satisfaction',
    'home.logistics.cta': 'Explore Our Solutions',
    
    // Footer
    'footer.description': 'Your strategic partner in the digital era. Transforming challenges into digital opportunities with innovative software solutions.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.contactInfo': 'Contact Info',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'footer.sitemap': 'Sitemap',
    
    // Contact Page
    'contact.title': 'Contact Us: Let\'s Talk About Your Next Big Project',
    'contact.subtitle': 'We are ready to listen to your challenges and turn them into tangible solutions. Fill out the form, call us, or email us. We will respond as soon as possible!',
    'contact.form.title': 'Send Us a Message',
    'contact.form.fullName': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.company': 'Company',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.success': 'Message Sent Successfully!',
    'contact.form.successDesc': 'Thank you for contacting us. We\'ll get back to you within 24 hours.',
    
    'contact.info.title': 'Get in Touch',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.office': 'Office',
    'contact.info.hours': 'Working Hours',
    'contact.info.emailDesc': 'Send us an email anytime',
    'contact.info.phoneDesc': 'Mon-Fri from 9am to 6pm',
    'contact.info.officeDesc': 'Come visit our office',
    'contact.info.hoursDesc': '9:00 AM - 6:00 PM (CEST)',
    
    // About Page
    'about.title': 'About Us: Experience, Passion, and Innovation at the Service of Your Business',
    'about.subtitle': 'Building the digital future together, one innovative solution at a time.',
    'about.story.title': 'Building the Digital Future with You',
    'about.vision.title': 'Our Vision:',
    'about.vision.desc': 'To be the benchmark in customized software solutions, recognized for our ability to innovate, the quality of our work, and the sustained success of our clients.',
    
    'about.values.title': 'Our Values Guide Everything We Do',
    'about.values.subtitle': 'These core principles shape how we work, interact with clients, and deliver solutions.',
    'about.values.excellence': 'Excellence',
    'about.values.innovation': 'Innovation',
    'about.values.integrity': 'Integrity',
    'about.values.customer': 'Customer Orientation',
    'about.values.collaboration': 'Collaboration',
    
    'about.team.title': 'Meet Our Experts',
    'about.team.subtitle': 'Our talented team combines deep technical expertise with business acumen to deliver exceptional results.',
    
    'about.culture.title': 'Our Culture of Innovation',
    'about.cta.title': 'Join the Family of Companies That Already Trust Us',
    'about.cta.subtitle': 'Experience the real impact of working with experts who are passionate about your success.',
    'about.cta.contact': 'Contact Us Today',
    
    // Services Page
    'services.title': 'Our Services: Your Path to Digital Excellence',
    'services.subtitle': 'At Doce Leguas, we combine deep technical expertise with strategic business vision to offer you software solutions that truly work. Explore our range of services designed to drive your growth.',
    'services.openbravo.title': 'Transform Your Management with Openbravo: Efficiency and Total Control',
    'services.openbravo.description': 'As Openbravo experts, we offer everything from initial implementation to advanced customization and continuous support. We maximize your ERP\'s potential to optimize your operations, from finances and sales to logistics and production.',
    'services.openbravo.benefits': 'Reduced operational costs, improved decision-making, guaranteed scalability, seamless integration.',
    'services.openbravo.point1': 'Implementation and Migration',
    'services.openbravo.point2': 'Customization and Module Development',
    'services.openbravo.point3': 'Support and Maintenance',
    'services.openbravo.point4': 'User Training',
    'services.openbravo.cta': 'Learn More about Openbravo',
    
    'services.odoo.title': 'Odoo: Centralize and Automate Your Business with Our Expertise',
    'services.odoo.description': 'Odoo is the ultimate suite of business applications. We help you exploit its full potential, adapting modules like CRM, accounting, project management, e-commerce, and more to your specific workflows.',
    'services.odoo.benefits': 'Increased productivity, 360° business view, reduced manual errors, scalability, and flexibility.',
    'services.odoo.point1': 'Consultancy and Requirements Analysis',
    'services.odoo.point2': 'Implementation and Configuration',
    'services.odoo.point3': 'Custom Module Development',
    'services.odoo.point4': 'Integration with Other Systems',
    'services.odoo.point5': 'Post-Implementation Support',
    'services.odoo.cta': 'Explore Our Odoo Solutions',
    
    'services.ai.title': 'Artificial Intelligence: From Data to Strategic Decisions',
    'services.ai.description': 'Unlock the power of your data with our AI solutions. From process automation (RPA) and predictive analysis to intelligent chatbots and computer vision, we create systems that learn, optimize, and generate value.',
    'services.ai.benefits': 'Operational optimization, improved customer experience, new revenue sources, competitive advantage.',
    'services.ai.point1': 'Machine Learning and Deep Learning',
    'services.ai.point2': 'Natural Language Processing (NLP)',
    'services.ai.point3': 'Computer Vision',
    'services.ai.point4': 'Robotic Process Automation (RPA)',
    'services.ai.point5': 'Chatbots and Virtual Assistants',
    'services.ai.cta': 'Discover Our AI Projects',
    
    'services.custom.title': 'Custom Software: The Perfect Solution for Unique Challenges',
    'services.custom.description': 'When standard solutions are not enough, we create applications that fit your processes and goals like a glove. From web and mobile applications to complex management systems, we design and develop robust, scalable, and user-centered software.',
    'services.custom.benefits': 'Unmatched efficiency, competitive advantage, total control over your technology, guaranteed security.',
    'services.custom.point1': 'Custom Analysis and Design',
    'services.custom.point2': 'Front-end and Back-end Development',
    'services.custom.point3': 'Mobile Applications (iOS/Android)',
    'services.custom.point4': 'Enterprise Management Systems (CRM, ERP, etc.)',
    'services.custom.point5': 'Legacy System Modernization',
    'services.custom.cta': 'Tell Us Your Idea',
    
    'services.consulting.title': 'Technological Consultancy: Strategy and Vision for Your Digital Future',
    'services.consulting.description': 'Our team of expert consultants will guide you in defining your technological roadmap. From infrastructure evaluation to selecting the most suitable solutions and project management, we offer a clear and strategic vision.',
    'services.consulting.benefits': 'Risk reduction, investment optimization, planned innovation, technological alignment with business goals.',
    'services.consulting.point1': 'Technological Audit',
    'services.consulting.point2': 'Strategic IT Planning',
    'services.consulting.point3': 'Technology and Vendor Selection',
    'services.consulting.point4': 'Software Project Management',
    'services.consulting.point5': 'Security and Cybersecurity',
    'services.consulting.cta': 'Consult Our Experts',
    
    'services.keyBenefits': 'Key Benefits:',
    'services.whatWeOffer': 'What We Offer:',
    'services.finalCta.title': 'No matter how complex your challenge is, we have the expertise to turn it into success.',
    'services.finalCta.subtitle': 'Let\'s talk about your next project and discover how we can help you achieve your goals.',
    'services.finalCta.contact': 'Contact Us',
    
    // Solutions Page
    'solutions.title': 'Comprehensive Solutions for Your Sector',
    'solutions.subtitle': 'We have developed packaged solutions that address the most common challenges in various industries, combining our experience in Openbravo, Odoo, AI, and custom development to offer you unprecedented value.',
    
    'solutions.retail.title': 'Retail Solution',
    'solutions.retail.subtitle': 'Optimize Your Supply Chain and Customer Experience',
    'solutions.retail.description': 'Comprehensive solution that integrates inventory management, point-of-sale systems, customer relationship management, and business intelligence to transform your retail operations.',
    'solutions.retail.feature1': 'Real-time inventory management',
    'solutions.retail.feature2': 'Integrated POS system',
    'solutions.retail.feature3': 'Customer loyalty programs',
    'solutions.retail.feature4': 'Sales analytics and reporting',
    'solutions.retail.feature5': 'Multi-channel integration',
    'solutions.retail.feature6': 'Supply chain optimization',
    'solutions.retail.benefit1': 'Reduce inventory costs by up to 25%',
    'solutions.retail.benefit2': 'Improve customer satisfaction',
    'solutions.retail.benefit3': 'Increase sales efficiency',
    'solutions.retail.benefit4': 'Better demand forecasting',
    
    'solutions.manufacturing.title': 'Manufacturing Solution',
    'solutions.manufacturing.subtitle': 'Total Control of Production and Resource Management',
    'solutions.manufacturing.description': 'End-to-end manufacturing solution that optimizes production planning, resource allocation, quality control, and maintenance scheduling for maximum operational efficiency.',
    'solutions.manufacturing.feature1': 'Production planning and scheduling',
    'solutions.manufacturing.feature2': 'Material resource planning (MRP)',
    'solutions.manufacturing.feature3': 'Quality management system',
    'solutions.manufacturing.feature4': 'Maintenance management',
    'solutions.manufacturing.feature5': 'Shop floor control',
    'solutions.manufacturing.feature6': 'Cost tracking and analysis',
    'solutions.manufacturing.benefit1': 'Increase production efficiency by 30%',
    'solutions.manufacturing.benefit2': 'Reduce waste and operational costs',
    'solutions.manufacturing.benefit3': 'Improve product quality',
    'solutions.manufacturing.benefit4': 'Optimize resource utilization',
    
    'solutions.services.title': 'Services Solution',
    'solutions.services.subtitle': 'Automate Your Processes and Improve Your Team\'s Productivity',
    'solutions.services.description': 'Tailored solution for service-based businesses that streamlines project management, resource allocation, client management, and billing processes.',
    'solutions.services.feature1': 'Project and task management',
    'solutions.services.feature2': 'Time tracking and billing',
    'solutions.services.feature3': 'Client relationship management',
    'solutions.services.feature4': 'Resource scheduling',
    'solutions.services.feature5': 'Document management',
    'solutions.services.feature6': 'Financial reporting',
    'solutions.services.benefit1': 'Increase team productivity by 40%',
    'solutions.services.benefit2': 'Improve client satisfaction',
    'solutions.services.benefit3': 'Streamline billing processes',
    'solutions.services.benefit4': 'Better project visibility',
    
    'solutions.keyFeatures': 'Key Features:',
    'solutions.expectedBenefits': 'Expected Benefits:',
    'solutions.learnMore': 'Learn More',
    
    'solutions.whyChoose.title': 'Why Choose Our Industry Solutions?',
    'solutions.whyChoose.expertise.title': 'Industry Expertise',
    'solutions.whyChoose.expertise.desc': 'Deep understanding of sector-specific challenges and requirements.',
    'solutions.whyChoose.results.title': 'Proven Results',
    'solutions.whyChoose.results.desc': 'Track record of successful implementations across various industries.',
    'solutions.whyChoose.scalable.title': 'Scalable Solutions',
    'solutions.whyChoose.scalable.desc': 'Solutions that grow with your business and adapt to changing needs.',
    'solutions.whyChoose.support.title': 'Comprehensive Support',
    'solutions.whyChoose.support.desc': 'Full lifecycle support from implementation to ongoing maintenance.',
    
    'solutions.cta.title': 'Ready to Transform Your Business?',
    'solutions.cta.subtitle': 'Discover how our industry-specific solutions can drive efficiency, reduce costs, and accelerate your growth.',
    'solutions.cta.getStarted': 'Get Started Today',
    
    // Projects Page
    'projects.title': 'Our Projects: Stories of Success and Transformation',
    'projects.subtitle': 'Each project is an opportunity to demonstrate our commitment to excellence. Here we present some of our most relevant works, showing how we have helped companies achieve their digital goals.',
    'projects.filter.all': 'All Projects',
    'projects.filter.openbravo': 'Openbravo',
    'projects.filter.odoo': 'Odoo',
    'projects.filter.ai': 'AI Solutions',
    'projects.filter.custom': 'Custom Development',
    
    'projects.halsted.title': 'Halsted Logistics Optimization',
    'projects.halsted.description': 'Complete Openbravo ERP implementation with custom modules for inventory management, resulting in 30% reduction in operational costs and 25% improvement in delivery times.',
    'projects.halsted.sector': 'Retail & Logistics',
    'projects.halsted.result1': '30% cost reduction',
    'projects.halsted.result2': '25% faster delivery',
    'projects.halsted.result3': '95% inventory accuracy',
    'projects.halsted.testimonial': 'Thanks to Doce Leguas, our operations have drastically improved. Their professionalism and knowledge are exceptional.',
    'projects.halsted.client': 'Brian, Operations Manager at Halsted',
    
    'projects.ai.title': 'AI-Powered Predictive Analytics',
    'projects.ai.description': 'Development of machine learning models for demand forecasting and predictive maintenance, enabling data-driven decision making and 40% improvement in operational efficiency.',
    'projects.ai.sector': 'Manufacturing',
    'projects.ai.result1': '40% efficiency gain',
    'projects.ai.result2': '60% better forecasting',
    'projects.ai.result3': '$2M cost savings',
    'projects.ai.testimonial': 'The AI solution they implemented exceeded all our expectations. The predictive capabilities have transformed our planning process.',
    'projects.ai.client': 'Maria Rodriguez, CTO at TechCorp Solutions',
    
    'projects.custom.title': 'Custom ERP Development',
    'projects.custom.description': 'Built from scratch a comprehensive ERP system tailored specifically for a growing services company, integrating project management, billing, and resource planning.',
    'projects.custom.sector': 'Professional Services',
    'projects.custom.result1': '45% productivity increase',
    'projects.custom.result2': '99.9% uptime',
    'projects.custom.result3': '100% custom fit',
    'projects.custom.testimonial': 'Finally, a system that works exactly how we do business. The custom ERP has streamlined all our processes.',
    'projects.custom.client': 'James Wilson, CEO at ProServ Consulting',
    
    'projects.odoo.title': 'Odoo Multi-Company Implementation',
    'projects.odoo.description': 'Comprehensive Odoo deployment across multiple subsidiaries with custom modules for consolidated reporting, inter-company transactions, and unified workflow management.',
    'projects.odoo.sector': 'Finance & Holding',
    'projects.odoo.result1': '5 companies unified',
    'projects.odoo.result2': '50% faster reporting',
    'projects.odoo.result3': '80% process automation',
    'projects.odoo.testimonial': 'The Odoo implementation has given us complete visibility across all our companies. Outstanding work.',
    'projects.odoo.client': 'Sarah Chen, CFO at GlobalTech Holdings',
    
    'projects.warehouse.title': 'Smart Warehouse Management',
    'projects.warehouse.description': 'AI-enhanced warehouse management system with computer vision for inventory tracking, automated reordering, and predictive maintenance of equipment.',
    'projects.warehouse.sector': 'Logistics & Distribution',
    'projects.warehouse.result1': '35% faster processing',
    'projects.warehouse.result2': '99% inventory accuracy',
    'projects.warehouse.result3': '20% cost reduction',
    'projects.warehouse.testimonial': 'The computer vision system has revolutionized our warehouse operations. Incredible accuracy and efficiency.',
    'projects.warehouse.client': 'Mike Torres, Warehouse Director at LogiFlow',
    
    'projects.migration.title': 'Cloud Migration & Modernization',
    'projects.migration.description': 'Complete legacy system modernization with cloud migration, API development, and mobile application creation for a traditional manufacturing company.',
    'projects.migration.sector': 'Manufacturing',
    'projects.migration.result1': '70% performance boost',
    'projects.migration.result2': '24/7 availability',
    'projects.migration.result3': 'Modern mobile access',
    'projects.migration.testimonial': 'They brought our 20-year-old system into the modern age. The transformation is remarkable.',
    'projects.migration.client': 'Robert Kim, IT Director at SteelWorks Inc',
    
    'projects.keyResults': 'Key Results:',
    'projects.viewCase': 'View Case Study',
    'projects.featured.title': 'Featured Success Story: Halsted Logistics Transformation',
    'projects.featured.challenge': 'The Challenge:',
    'projects.featured.challengeDesc': 'Halsted was struggling with manual inventory processes, leading to stockouts, overstock situations, and delayed deliveries that were affecting customer satisfaction.',
    'projects.featured.solution': 'Our Solution:',
    'projects.featured.solutionDesc': 'We implemented a comprehensive Openbravo ERP system with custom modules for real-time inventory tracking, automated reordering, and integrated logistics management.',
    'projects.featured.results': 'Results Achieved:',
    'projects.featured.costReduction': 'Cost Reduction',
    'projects.featured.fasterDelivery': 'Faster Delivery',
    'projects.cta.title': 'Let\'s Talk About Your Challenge',
    'projects.cta.subtitle': 'We can help you achieve similar results. Every great project starts with a conversation.',
    'projects.cta.contact': 'Contact Us Today',
    
    // ChatBot
    'chatbot.title': 'Doce Leguas Assistant',
    'chatbot.subtitle': 'How can we help you?',
    'chatbot.welcome': 'Hello! I\'m your virtual assistant. How can I help you today? You can ask me about our services, solutions, or any questions about Doce Leguas.',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.open': 'Open chat',
    'chatbot.close': 'Close chat',
    'chatbot.defaultResponse': 'Thank you for your message. Our team will get back to you soon with more information.',
    'chatbot.errorMessage': 'I\'m sorry, I\'m having trouble connecting right now. Please try again later or contact us directly.',
  },
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.solutions': 'Soluciones',
    'nav.projects': 'Proyectos',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.getStarted': 'Comenzar',
    
    // Home Page
    'home.hero.title': 'Impulsa Tu Negocio con Soluciones de Software Innovadoras',
    'home.hero.subtitle': 'Transformamos tus desafíos en oportunidades digitales. Expertos en Openbravo, Odoo, Inteligencia Artificial y desarrollo personalizado para una eficiencia sin precedentes.',
    'home.hero.viewServices': 'Ver Nuestros Servicios',
    'home.hero.startProject': 'Iniciar un Proyecto',
    
    'home.valueProps.title': 'Tu Socio Estratégico en la Era Digital',
    'home.valueProps.subtitle': 'En Doce Leguas, entendemos que cada negocio es único. Ofrecemos más que desarrollo de software: proporcionamos soluciones personalizadas que optimizan procesos, reducen costos y abren nuevas vías de crecimiento.',
    'home.valueProps.innovation': 'Innovación Constante',
    'home.valueProps.innovation.desc': 'Siempre a la vanguardia de las últimas tecnologías.',
    'home.valueProps.custom': 'Soluciones Personalizadas',
    'home.valueProps.custom.desc': 'Desarrollos que se adaptan perfectamente a tus necesidades.',
    'home.valueProps.results': 'Resultados Comprobados',
    'home.valueProps.results.desc': 'Impacto real en la eficiencia y rentabilidad de tu empresa.',
    'home.valueProps.team': 'Equipo Experto',
    'home.valueProps.team.desc': 'Profesionales altamente calificados y dedicados.',
    
    'home.services.title': '¿Qué Podemos Hacer Por Ti?',
    'home.services.subtitle': 'Explora nuestra amplia gama de servicios diseñados para transformar las operaciones de tu negocio.',
    'home.services.openbravo': 'Desarrollo Openbravo',
    'home.services.openbravo.desc': 'Maximiza la eficiencia de tu ERP con nuestros especialistas.',
    'home.services.odoo': 'Implementación Odoo',
    'home.services.odoo.desc': 'Automatiza y centraliza la gestión de tu negocio.',
    'home.services.ai': 'Aplicaciones de IA',
    'home.services.ai.desc': 'Transforma datos en decisiones estratégicas y operaciones inteligentes.',
    'home.services.custom': 'Desarrollo Personalizado',
    'home.services.custom.desc': 'Crea la herramienta perfecta para tus desafíos únicos.',
    'home.services.n8n': 'Flujos de Trabajo N8n',
    'home.services.n8n.desc': 'Automatiza procesos empresariales complejos con potente automatización de flujos de trabajo.',
    'home.services.automation': 'Automatización Empresarial',
    'home.services.automation.desc': 'Optimiza operaciones y elimina tareas manuales con automatización inteligente.',
    'home.services.learnMore': 'Saber Más',
    
    'home.projects.title': 'Resultados Que Hablan Por Sí Mismos',
    'home.projects.subtitle': 'Descubre cómo hemos ayudado a las empresas a lograr sus objetivos de transformación digital.',
    'home.projects.viewCase': 'Ver Caso de Estudio',
    
    'home.testimonials.title': 'Lo Que Dicen Nuestros Clientes',
    
    'home.cta.title': '¿Listo Para Llevar Tu Negocio al Siguiente Nivel?',
    'home.cta.subtitle': 'Permítenos entender tus desafíos y ofrecerte una solución que marque la diferencia. ¡Contáctanos hoy para una consulta sin compromiso!',
    'home.cta.schedule': 'Programar una Reunión',
    'home.cta.contact': 'Contáctanos Ahora',
    
    // Logistics & Retail Section
    'home.logistics.title': 'Soluciones Especializadas para Logística y Retail',
    'home.logistics.subtitle': 'Transforma tu cadena de suministro y operaciones retail con nuestra experiencia específica del sector y soluciones tecnológicas de vanguardia.',
    'home.logistics.supply.title': 'Optimización de Cadena de Suministro',
    'home.logistics.supply.desc': 'Optimiza tus operaciones logísticas con gestión inteligente de inventario y flujos de trabajo automatizados.',
    'home.logistics.supply.feature1': 'Seguimiento de inventario en tiempo real',
    'home.logistics.supply.feature2': 'Sistemas de reorden automatizado',
    'home.logistics.supply.feature3': 'Planificación predictiva de demanda',
    'home.logistics.retail.title': 'Sistemas de Gestión Retail',
    'home.logistics.retail.desc': 'Mejora la experiencia del cliente y aumenta las ventas con soluciones retail integradas.',
    'home.logistics.retail.feature1': 'Sistemas POS multicanal',
    'home.logistics.retail.feature2': 'Programas de fidelización',
    'home.logistics.retail.feature3': 'Análisis y reportes de ventas',
    'home.logistics.expertise.title': 'Experiencia en la Industria',
    'home.logistics.expertise.desc': 'Años de experiencia entregando proyectos exitosos en los sectores de logística y retail.',
    'home.logistics.expertise.stat1': 'Proyectos Entregados',
    'home.logistics.expertise.stat2': 'Satisfacción del Cliente',
    'home.logistics.cta': 'Explorar Nuestras Soluciones',
    
    // Footer
    'footer.description': 'Tu socio estratégico en la era digital. Transformando desafíos en oportunidades digitales con soluciones de software innovadoras.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Nuestros Servicios',
    'footer.contactInfo': 'Información de Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.legal': 'Aviso Legal',
    'footer.sitemap': 'Mapa del Sitio',
    
    // Contact Page
    'contact.title': 'Contáctanos: Hablemos de Tu Próximo Gran Proyecto',
    'contact.subtitle': 'Estamos listos para escuchar tus desafíos y convertirlos en soluciones tangibles. ¡Completa el formulario, llámanos o envíanos un email. Te responderemos lo antes posible!',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.fullName': 'Nombre Completo',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Teléfono',
    'contact.form.company': 'Empresa',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.form.success': '¡Mensaje Enviado Exitosamente!',
    'contact.form.successDesc': 'Gracias por contactarnos. Te responderemos dentro de 24 horas.',
    
    'contact.info.title': 'Ponte en Contacto',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Teléfono',
    'contact.info.office': 'Oficina',
    'contact.info.hours': 'Horario de Trabajo',
    'contact.info.emailDesc': 'Envíanos un email en cualquier momento',
    'contact.info.phoneDesc': 'Lun-Vie de 9am a 6pm',
    'contact.info.officeDesc': 'Ven a visitar nuestra oficina',
    'contact.info.hoursDesc': '9:00 AM - 6:00 PM (CEST)',
    
    // About Page
    'about.title': 'Nosotros: Experiencia, Pasión e Innovación al Servicio de Tu Negocio',
    'about.subtitle': 'Construyendo el futuro digital juntos, una solución innovadora a la vez.',
    'about.story.title': 'Construyendo el Futuro Digital Contigo',
    'about.vision.title': 'Nuestra Visión:',
    'about.vision.desc': 'Ser el referente en soluciones de software personalizadas, reconocidos por nuestra capacidad de innovar, la calidad de nuestro trabajo y el éxito sostenido de nuestros clientes.',
    
    'about.values.title': 'Nuestros Valores Guían Todo Lo Que Hacemos',
    'about.values.subtitle': 'Estos principios fundamentales dan forma a cómo trabajamos, interactuamos con los clientes y entregamos soluciones.',
    'about.values.excellence': 'Excelencia',
    'about.values.innovation': 'Innovación',
    'about.values.integrity': 'Integridad',
    'about.values.customer': 'Orientación al Cliente',
    'about.values.collaboration': 'Colaboración',
    
    'about.team.title': 'Conoce a Nuestros Expertos',
    'about.team.subtitle': 'Nuestro talentoso equipo combina profunda experiencia técnica con conocimiento empresarial para entregar resultados excepcionales.',
    
    'about.culture.title': 'Nuestra Cultura de Innovación',
    'about.cta.title': 'Únete a la Familia de Empresas Que Ya Confían en Nosotros',
    'about.cta.subtitle': 'Experimenta el impacto real de trabajar con expertos apasionados por tu éxito.',
    'about.cta.contact': 'Contáctanos Hoy',
    
    // Services Page
    'services.title': 'Nuestros Servicios: Tu Camino Hacia la Excelencia Digital',
    'services.subtitle': 'En Doce Leguas, combinamos profunda experiencia técnica con visión estratégica empresarial para ofrecerte soluciones de software que realmente funcionan. Explora nuestra gama de servicios diseñados para impulsar tu crecimiento.',
    'services.openbravo.title': 'Transforma Tu Gestión con Openbravo: Eficiencia y Control Total',
    'services.openbravo.description': 'Como expertos en Openbravo, ofrecemos desde la implementación inicial hasta la personalización avanzada y el soporte continuo. Maximizamos el potencial de tu ERP para optimizar tus operaciones, desde finanzas y ventas hasta logística y producción.',
    'services.openbravo.benefits': 'Costos operativos reducidos, mejor toma de decisiones, escalabilidad garantizada, integración perfecta.',
    'services.openbravo.point1': 'Implementación y Migración',
    'services.openbravo.point2': 'Personalización y Desarrollo de Módulos',
    'services.openbravo.point3': 'Soporte y Mantenimiento',
    'services.openbravo.point4': 'Capacitación de Usuarios',
    'services.openbravo.cta': 'Saber Más sobre Openbravo',
    
    'services.odoo.title': 'Odoo: Centraliza y Automatiza Tu Negocio con Nuestra Experiencia',
    'services.odoo.description': 'Odoo es la suite definitiva de aplicaciones empresariales. Te ayudamos a explotar todo su potencial, adaptando módulos como CRM, contabilidad, gestión de proyectos, e-commerce y más a tus flujos de trabajo específicos.',
    'services.odoo.benefits': 'Mayor productividad, visión 360° del negocio, reducción de errores manuales, escalabilidad y flexibilidad.',
    'services.odoo.point1': 'Consultoría y Análisis de Requerimientos',
    'services.odoo.point2': 'Implementación y Configuración',
    'services.odoo.point3': 'Desarrollo de Módulos Personalizados',
    'services.odoo.point4': 'Integración con Otros Sistemas',
    'services.odoo.point5': 'Soporte Post-Implementación',
    'services.odoo.cta': 'Explorar Nuestras Soluciones Odoo',
    
    'services.ai.title': 'Inteligencia Artificial: De Datos a Decisiones Estratégicas',
    'services.ai.description': 'Desbloquea el poder de tus datos con nuestras soluciones de IA. Desde automatización de procesos (RPA) y análisis predictivo hasta chatbots inteligentes y visión por computadora, creamos sistemas que aprenden, optimizan y generan valor.',
    'services.ai.benefits': 'Optimización operacional, mejor experiencia del cliente, nuevas fuentes de ingresos, ventaja competitiva.',
    'services.ai.point1': 'Aprendizaje Automático y Aprendizaje Profundo',
    'services.ai.point2': 'Procesamiento de Lenguaje Natural (NLP)',
    'services.ai.point3': 'Visión por Computadora',
    'services.ai.point4': 'Automatización Robótica de Procesos (RPA)',
    'services.ai.point5': 'Chatbots y Asistentes Virtuales',
    'services.ai.cta': 'Descubrir Nuestros Proyectos de IA',
    
    'services.custom.title': 'Software Personalizado: La Solución Perfecta para Desafíos Únicos',
    'services.custom.description': 'Cuando las soluciones estándar no son suficientes, creamos aplicaciones que se ajustan a tus procesos y objetivos como un guante. Desde aplicaciones web y móviles hasta sistemas de gestión complejos, diseñamos y desarrollamos software robusto, escalable y centrado en el usuario.',
    'services.custom.benefits': 'Eficiencia inigualable, ventaja competitiva, control total sobre tu tecnología, seguridad garantizada.',
    'services.custom.point1': 'Análisis y Diseño Personalizado',
    'services.custom.point2': 'Desarrollo Front-end y Back-end',
    'services.custom.point3': 'Aplicaciones Móviles (iOS/Android)',
    'services.custom.point4': 'Sistemas de Gestión Empresarial (CRM, ERP, etc.)',
    'services.custom.point5': 'Modernización de Sistemas Legacy',
    'services.custom.cta': 'Cuéntanos Tu Idea',
    
    'services.consulting.title': 'Consultoría Tecnológica: Estrategia y Visión para Tu Futuro Digital',
    'services.consulting.description': 'Nuestro equipo de consultores expertos te guiará en la definición de tu hoja de ruta tecnológica. Desde la evaluación de infraestructura hasta la selección de las soluciones más adecuadas y la gestión de proyectos, ofrecemos una visión clara y estratégica.',
    'services.consulting.benefits': 'Reducción de riesgos, optimización de inversiones, innovación planificada, alineación tecnológica con objetivos empresariales.',
    'services.consulting.point1': 'Auditoría Tecnológica',
    'services.consulting.point2': 'Planificación Estratégica de TI',
    'services.consulting.point3': 'Selección de Tecnología y Proveedores',
    'services.consulting.point4': 'Gestión de Proyectos de Software',
    'services.consulting.point5': 'Seguridad y Ciberseguridad',
    'services.consulting.cta': 'Consultar Nuestros Expertos',
    
    'services.keyBenefits': 'Beneficios Clave:',
    'services.whatWeOffer': 'Lo Que Ofrecemos:',
    'services.finalCta.title': 'No importa qué tan complejo sea tu desafío, tenemos la experiencia para convertirlo en éxito.',
    'services.finalCta.subtitle': 'Hablemos sobre tu próximo proyecto y descubramos cómo podemos ayudarte a lograr tus objetivos.',
    'services.finalCta.contact': 'Contáctanos',
    
    // Solutions Page
    'solutions.title': 'Soluciones Integrales para Tu Sector',
    'solutions.subtitle': 'Hemos desarrollado soluciones empaquetadas que abordan los desafíos más comunes en varias industrias, combinando nuestra experiencia en Openbravo, Odoo, IA y desarrollo personalizado para ofrecerte un valor sin precedentes.',
    
    'solutions.retail.title': 'Solución Retail',
    'solutions.retail.subtitle': 'Optimiza Tu Cadena de Suministro y Experiencia del Cliente',
    'solutions.retail.description': 'Solución integral que integra gestión de inventario, sistemas de punto de venta, gestión de relaciones con clientes e inteligencia empresarial para transformar tus operaciones retail.',
    'solutions.retail.feature1': 'Gestión de inventario en tiempo real',
    'solutions.retail.feature2': 'Sistema POS integrado',
    'solutions.retail.feature3': 'Programas de fidelización de clientes',
    'solutions.retail.feature4': 'Análisis y reportes de ventas',
    'solutions.retail.feature5': 'Integración multicanal',
    'solutions.retail.feature6': 'Optimización de cadena de suministro',
    'solutions.retail.benefit1': 'Reducir costos de inventario hasta un 25%',
    'solutions.retail.benefit2': 'Mejorar la satisfacción del cliente',
    'solutions.retail.benefit3': 'Aumentar la eficiencia de ventas',
    'solutions.retail.benefit4': 'Mejor pronóstico de demanda',
    
    'solutions.manufacturing.title': 'Solución de Manufactura',
    'solutions.manufacturing.subtitle': 'Control Total de Producción y Gestión de Recursos',
    'solutions.manufacturing.description': 'Solución de manufactura integral que optimiza la planificación de producción, asignación de recursos, control de calidad y programación de mantenimiento para máxima eficiencia operacional.',
    'solutions.manufacturing.feature1': 'Planificación y programación de producción',
    'solutions.manufacturing.feature2': 'Planificación de recursos materiales (MRP)',
    'solutions.manufacturing.feature3': 'Sistema de gestión de calidad',
    'solutions.manufacturing.feature4': 'Gestión de mantenimiento',
    'solutions.manufacturing.feature5': 'Control de planta',
    'solutions.manufacturing.feature6': 'Seguimiento y análisis de costos',
    'solutions.manufacturing.benefit1': 'Aumentar eficiencia de producción en 30%',
    'solutions.manufacturing.benefit2': 'Reducir desperdicios y costos operativos',
    'solutions.manufacturing.benefit3': 'Mejorar la calidad del producto',
    'solutions.manufacturing.benefit4': 'Optimizar la utilización de recursos',
    
    'solutions.services.title': 'Solución de Servicios',
    'solutions.services.subtitle': 'Automatiza Tus Procesos y Mejora la Productividad de Tu Equipo',
    'solutions.services.description': 'Solución personalizada para empresas basadas en servicios que optimiza la gestión de proyectos, asignación de recursos, gestión de clientes y procesos de facturación.',
    'solutions.services.feature1': 'Gestión de proyectos y tareas',
    'solutions.services.feature2': 'Seguimiento de tiempo y facturación',
    'solutions.services.feature3': 'Gestión de relaciones con clientes',
    'solutions.services.feature4': 'Programación de recursos',
    'solutions.services.feature5': 'Gestión de documentos',
    'solutions.services.feature6': 'Reportes financieros',
    'solutions.services.benefit1': 'Aumentar productividad del equipo en 40%',
    'solutions.services.benefit2': 'Mejorar satisfacción del cliente',
    'solutions.services.benefit3': 'Optimizar procesos de facturación',
    'solutions.services.benefit4': 'Mejor visibilidad de proyectos',
    
    'solutions.keyFeatures': 'Características Clave:',
    'solutions.expectedBenefits': 'Beneficios Esperados:',
    'solutions.learnMore': 'Saber Más',
    
    'solutions.whyChoose.title': '¿Por Qué Elegir Nuestras Soluciones Industriales?',
    'solutions.whyChoose.expertise.title': 'Experiencia en la Industria',
    'solutions.whyChoose.expertise.desc': 'Comprensión profunda de desafíos y requerimientos específicos del sector.',
    'solutions.whyChoose.results.title': 'Resultados Comprobados',
    'solutions.whyChoose.results.desc': 'Historial de implementaciones exitosas en varias industrias.',
    'solutions.whyChoose.scalable.title': 'Soluciones Escalables',
    'solutions.whyChoose.scalable.desc': 'Soluciones que crecen con tu negocio y se adaptan a necesidades cambiantes.',
    'solutions.whyChoose.support.title': 'Soporte Integral',
    'solutions.whyChoose.support.desc': 'Soporte completo del ciclo de vida desde implementación hasta mantenimiento continuo.',
    
    'solutions.cta.title': '¿Listo para Transformar Tu Negocio?',
    'solutions.cta.subtitle': 'Descubre cómo nuestras soluciones específicas de la industria pueden impulsar la eficiencia, reducir costos y acelerar tu crecimiento.',
    'solutions.cta.getStarted': 'Comenzar Hoy',
    
    // Projects Page
    'projects.title': 'Nuestros Proyectos: Historias de Éxito y Transformación',
    'projects.subtitle': 'Cada proyecto es una oportunidad para demostrar nuestro compromiso con la excelencia. Aquí presentamos algunos de nuestros trabajos más relevantes, mostrando cómo hemos ayudado a las empresas a lograr sus objetivos digitales.',
    'projects.filter.all': 'Todos los Proyectos',
    'projects.filter.openbravo': 'Openbravo',
    'projects.filter.odoo': 'Odoo',
    'projects.filter.ai': 'Soluciones de IA',
    'projects.filter.custom': 'Desarrollo Personalizado',
    
    'projects.halsted.title': 'Optimización Logística de Halsted',
    'projects.halsted.description': 'Implementación completa de ERP Openbravo con módulos personalizados para gestión de inventario, resultando en 30% de reducción en costos operativos y 25% de mejora en tiempos de entrega.',
    'projects.halsted.sector': 'Retail y Logística',
    'projects.halsted.result1': '30% reducción de costos',
    'projects.halsted.result2': '25% entrega más rápida',
    'projects.halsted.result3': '95% precisión de inventario',
    'projects.halsted.testimonial': 'Gracias a Doce Leguas, nuestras operaciones han mejorado drásticamente. Su profesionalismo y conocimiento son excepcionales.',
    'projects.halsted.client': 'Brian, Gerente de Operaciones en Halsted',
    
    'projects.ai.title': 'Análisis Predictivo Potenciado por IA',
    'projects.ai.description': 'Desarrollo de modelos de aprendizaje automático para pronóstico de demanda y mantenimiento predictivo, habilitando toma de decisiones basada en datos y 40% de mejora en eficiencia operacional.',
    'projects.ai.sector': 'Manufactura',
    'projects.ai.result1': '40% ganancia en eficiencia',
    'projects.ai.result2': '60% mejor pronóstico',
    'projects.ai.result3': '$2M ahorro en costos',
    'projects.ai.testimonial': 'La solución de IA que implementaron superó todas nuestras expectativas. Las capacidades predictivas han transformado nuestro proceso de planificación.',
    'projects.ai.client': 'María Rodríguez, CTO en TechCorp Solutions',
    
    'projects.custom.title': 'Desarrollo de ERP Personalizado',
    'projects.custom.description': 'Construido desde cero un sistema ERP integral adaptado específicamente para una empresa de servicios en crecimiento, integrando gestión de proyectos, facturación y planificación de recursos.',
    'projects.custom.sector': 'Servicios Profesionales',
    'projects.custom.result1': '45% aumento de productividad',
    'projects.custom.result2': '99.9% tiempo de actividad',
    'projects.custom.result3': '100% ajuste personalizado',
    'projects.custom.testimonial': 'Finalmente, un sistema que funciona exactamente como hacemos negocios. El ERP personalizado ha optimizado todos nuestros procesos.',
    'projects.custom.client': 'James Wilson, CEO en ProServ Consulting',
    
    'projects.odoo.title': 'Implementación Multi-Empresa de Odoo',
    'projects.odoo.description': 'Despliegue integral de Odoo en múltiples subsidiarias con módulos personalizados para reportes consolidados, transacciones inter-empresariales y gestión unificada de flujos de trabajo.',
    'projects.odoo.sector': 'Finanzas y Holding',
    'projects.odoo.result1': '5 empresas unificadas',
    'projects.odoo.result2': '50% reportes más rápidos',
    'projects.odoo.result3': '80% automatización de procesos',
    'projects.odoo.testimonial': 'La implementación de Odoo nos ha dado visibilidad completa en todas nuestras empresas. Trabajo excepcional.',
    'projects.odoo.client': 'Sarah Chen, CFO en GlobalTech Holdings',
    
    'projects.warehouse.title': 'Gestión Inteligente de Almacén',
    'projects.warehouse.description': 'Sistema de gestión de almacén mejorado con IA con visión por computadora para seguimiento de inventario, reorden automatizado y mantenimiento predictivo de equipos.',
    'projects.warehouse.sector': 'Logística y Distribución',
    'projects.warehouse.result1': '35% procesamiento más rápido',
    'projects.warehouse.result2': '99% precisión de inventario',
    'projects.warehouse.result3': '20% reducción de costos',
    'projects.warehouse.testimonial': 'El sistema de visión por computadora ha revolucionado nuestras operaciones de almacén. Precisión y eficiencia increíbles.',
    'projects.warehouse.client': 'Mike Torres, Director de Almacén en LogiFlow',
    
    'projects.migration.title': 'Migración a la Nube y Modernización',
    'projects.migration.description': 'Modernización completa del sistema legacy con migración a la nube, desarrollo de API y creación de aplicación móvil para una empresa manufacturera tradicional.',
    'projects.migration.sector': 'Manufactura',
    'projects.migration.result1': '70% mejora en rendimiento',
    'projects.migration.result2': 'Disponibilidad 24/7',
    'projects.migration.result3': 'Acceso móvil moderno',
    'projects.migration.testimonial': 'Trajeron nuestro sistema de 20 años a la era moderna. La transformación es notable.',
    'projects.migration.client': 'Robert Kim, Director de TI en SteelWorks Inc',
    
    'projects.keyResults': 'Resultados Clave:',
    'projects.viewCase': 'Ver Caso de Estudio',
    'projects.featured.title': 'Historia de Éxito Destacada: Transformación Logística de Halsted',
    'projects.featured.challenge': 'El Desafío:',
    'projects.featured.challengeDesc': 'Halsted luchaba con procesos manuales de inventario, llevando a desabastecimientos, situaciones de sobrestock y entregas retrasadas que afectaban la satisfacción del cliente.',
    'projects.featured.solution': 'Nuestra Solución:',
    'projects.featured.solutionDesc': 'Implementamos un sistema ERP Openbravo integral con módulos personalizados para seguimiento de inventario en tiempo real, reorden automatizado y gestión logística integrada.',
    'projects.featured.results': 'Resultados Logrados:',
    'projects.featured.costReduction': 'Reducción de Costos',
    'projects.featured.fasterDelivery': 'Entrega Más Rápida',
    'projects.cta.title': 'Hablemos Sobre Tu Desafío',
    'projects.cta.subtitle': 'Podemos ayudarte a lograr resultados similares. Todo gran proyecto comienza con una conversación.',
    'projects.cta.contact': 'Contáctanos Hoy',
    
    // ChatBot
    'chatbot.title': 'Asistente Doce Leguas',
    'chatbot.subtitle': '¿Cómo podemos ayudarte?',
    'chatbot.welcome': '¡Hola! Soy tu asistente virtual. ¿Cómo puedo ayudarte hoy? Puedes preguntarme sobre nuestros servicios, soluciones, o cualquier consulta sobre Doce Leguas.',
    'chatbot.placeholder': 'Escribe tu mensaje...',
    'chatbot.open': 'Abrir chat',
    'chatbot.close': 'Cerrar chat',
    'chatbot.defaultResponse': 'Gracias por tu mensaje. Nuestro equipo te responderá pronto con más información.',
    'chatbot.errorMessage': 'Lo siento, tengo problemas de conexión en este momento. Por favor intenta más tarde o contáctanos directamente.',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};