import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.solutions': 'Solutions',
    'nav.projects': 'Projects',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',

    // Home Page
    'home.hero.title': 'Transform Your Business with Innovative Software Solutions',
    'home.hero.subtitle': 'We specialize in Openbravo, Odoo, AI solutions, and custom development to drive your digital transformation.',
    'home.hero.viewServices': 'View Our Services',
    'home.hero.startProject': 'Start Your Project',

    'home.valueProps.title': 'Why Choose Doce Leguas?',
    'home.valueProps.subtitle': 'We combine technical expertise with strategic vision to deliver solutions that truly make a difference.',
    'home.valueProps.innovation': 'Innovation',
    'home.valueProps.innovation.desc': 'We stay at the forefront of technology to offer cutting-edge solutions.',
    'home.valueProps.custom': 'Customization',
    'home.valueProps.custom.desc': 'Every solution is tailored to your specific needs and business processes.',
    'home.valueProps.results': 'Proven Results',
    'home.valueProps.results.desc': 'Our track record speaks for itself with successful implementations.',
    'home.valueProps.team': 'Expert Team',
    'home.valueProps.team.desc': 'Certified professionals with years of experience in enterprise solutions.',

    'home.services.title': 'Our Core Services',
    'home.services.subtitle': 'Comprehensive solutions to transform your business operations.',
    'home.services.openbravo': 'Openbravo ERP',
    'home.services.openbravo.desc': 'Complete ERP implementation and customization for enterprise management.',
    'home.services.odoo': 'Odoo Solutions',
    'home.services.odoo.desc': 'Comprehensive business management with Odoo\'s integrated suite.',
    'home.services.ai': 'AI Solutions',
    'home.services.ai.desc': 'Intelligent automation, virtual agents, and AI-powered workflows for data-driven decision making.',
    'home.services.custom': 'Custom Development',
    'home.services.custom.desc': 'Tailored software solutions built specifically for your needs.',
    'home.services.n8n': 'n8n Automation',
    'home.services.n8n.desc': 'Workflow automation and system integration with n8n.',
    'home.services.automation': 'Process Automation',
    'home.services.automation.desc': 'Streamline operations with intelligent automation solutions.',
    'home.services.learnMore': 'Learn More',

    'home.projects.title': 'Success Stories',
    'home.projects.subtitle': 'See how we\'ve helped businesses achieve their digital transformation goals.',
    'home.projects.viewCase': 'View Case Study',

    'home.testimonials.title': 'What Our Clients Say',

    'home.logistics.title': 'Specialized Solutions for Logistics & Retail',
    'home.logistics.subtitle': 'Industry-specific expertise to optimize your operations and drive growth.',
    'home.logistics.supply.title': 'Supply Chain Optimization',
    'home.logistics.supply.desc': 'Streamline your logistics operations with intelligent supply chain management.',
    'home.logistics.supply.feature1': 'Real-time inventory tracking',
    'home.logistics.supply.feature2': 'Automated reordering systems',
    'home.logistics.supply.feature3': 'Predictive demand planning',
    'home.logistics.retail.title': 'Retail Management',
    'home.logistics.retail.desc': 'Complete retail solutions from POS to customer management.',
    'home.logistics.retail.feature1': 'Integrated POS systems',
    'home.logistics.retail.feature2': 'Customer loyalty programs',
    'home.logistics.retail.feature3': 'Multi-channel integration',
    'home.logistics.expertise.title': 'Industry Expertise',
    'home.logistics.expertise.desc': 'Deep understanding of logistics and retail challenges.',
    'home.logistics.expertise.stat1': 'Projects',
    'home.logistics.expertise.stat2': 'Success Rate',
    'home.logistics.cta': 'Explore Our Solutions',

    'home.cta.title': 'Ready to Transform Your Business?',
    'home.cta.subtitle': 'Let\'s discuss how we can help you achieve your digital transformation goals.',
    'home.cta.schedule': 'Schedule a Consultation',
    'home.cta.contact': 'Contact Us',

    // About Page
    'about.title': 'About Doce Leguas: Innovation, Excellence, and Results',
    'about.subtitle': 'We are a team of passionate professionals dedicated to transforming businesses through innovative technology solutions.',
    'about.story.title': 'Our Story',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be the benchmark in customized software solutions, recognized for our ability to innovate, the quality of our work, and the sustained success of our clients.',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles that guide everything we do.',
    'about.values.excellence': 'Excellence',
    'about.values.innovation': 'Innovation',
    'about.values.integrity': 'Integrity',
    'about.values.customer': 'Customer Focus',
    'about.values.collaboration': 'Collaboration',
    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'Experienced professionals committed to your success.',
    'about.culture.title': 'Our Company Culture',
    'about.cta.title': 'Ready to Work Together?',
    'about.cta.subtitle': 'Let\'s discuss how our team can help you achieve your business goals.',
    'about.cta.contact': 'Contact Our Team',

    // Team member details
    'about.team.nono.position': 'Lead ERP Architect',
    'about.team.nono.description': 'Certified Openbravo and Odoo expert with extensive experience in complex ERP implementations across various industries.',
    'about.team.mark.position': 'Lead AI Architect', 
    'about.team.mark.description': 'Specialist in artificial intelligence and machine learning with 10+ years developing intelligent solutions for enterprise clients.',
    'about.team.rafael.position': 'Lead Retail Architect',
    'about.team.rafael.description': 'Expert in retail solutions and digital transformation with extensive experience optimizing inventory management, and customer experience across retail organizations.',
    'about.team.maarten.position': 'Supply Chain Consultant',
    'about.team.maarten.description': 'Expert in supply chain optimization and logistics management with deep knowledge of warehouse operations, distribution networks, and inventory control systems.',

    // Contact Page
    'contact.title': 'Contact Us: Let\'s Start Your Digital Transformation',
    'contact.subtitle': 'We\'re here to help you achieve your business goals. Get in touch with our team of experts.',
    'contact.form.title': 'Send Us a Message',
    'contact.form.fullName': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.company': 'Company',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.success': 'Message Sent Successfully!',
    'contact.form.successDesc': 'Thank you for contacting us. We\'ll get back to you within 24 hours.',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.emailDesc': 'Send us an email anytime',
    'contact.info.phone': 'Phone',
    'contact.info.phoneDesc': 'Call us during business hours',
    'contact.info.office': 'Office',
    'contact.info.officeDesc': 'Visit our office',
    'contact.info.hours': 'Business Hours',
    'contact.info.hoursDesc': '9:00 AM - 6:00 PM',

    // Footer
    'footer.description': 'Transforming businesses through innovative software solutions and expert consulting.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contactInfo': 'Contact Info',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'footer.sitemap': 'Sitemap',

    // ChatBot
    'chatbot.title': 'Doce Leguas Assistant',
    'chatbot.subtitle': 'How can we help you?',
    'chatbot.welcome': 'Hello! I\'m here to help you with any questions about our services. How can I assist you today?',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.open': 'Open chat',
    'chatbot.close': 'Close chat',
    'chatbot.defaultResponse': 'Thank you for your message. Our team will get back to you soon.',
    'chatbot.errorMessage': 'Sorry, I\'m having trouble connecting right now. Please try again later or contact us directly.',

    // Services Page
    'services.title': 'Our Services: Your Path to Digital Excellence',
    'services.subtitle': 'At Doce Leguas, we combine deep technical expertise with strategic business vision to offer you software solutions that truly work. Explore our range of services designed to drive your growth.',

    // Solutions Page
    'solutions.title': 'Comprehensive Solutions for Your Sector',
    'solutions.subtitle': 'We have developed packaged solutions that address the most common challenges in various industries, combining our experience in Openbravo, Odoo, AI, and custom development to offer you unprecedented value.',

    // Projects Page
    'projects.title': 'Our Projects: Stories of Success and Transformation',
    'projects.subtitle': 'Each project is an opportunity to demonstrate our commitment to excellence. Here we present some of our most relevant works, showing how we have helped companies achieve their digital goals.',

    // Services Page - Complete content
    'services.openbravo.title': 'Transform Your Management with Openbravo: Efficiency and Total Control',
    'services.openbravo.benefits': 'Reduced operational costs, improved decision-making, guaranteed scalability, seamless integration.',
    'services.openbravo.point1': 'Implementation and Migration',
    'services.openbravo.point2': 'Customization and Module Development',
    'services.openbravo.point3': 'Support and Maintenance',
    'services.openbravo.point4': 'User Training',
    'services.openbravo.cta': 'Learn More about Openbravo',

    'services.odoo.title': 'Odoo: Centralize and Automate Your Business with Our Expertise',
    'services.odoo.description': 'Odoo is the ultimate suite of business applications. We help you exploit its full potential, adapting modules like CRM, accounting, project management, e-commerce, and more to your specific workflows.',
    'services.odoo.benefits': 'Increased productivity, 360° business view, reduced manual errors, scalability, and flexibility.',
    'services.odoo.point1': 'Consultancy and Requirements Analysis',
    'services.odoo.point2': 'Implementation and Configuration',
    'services.odoo.point3': 'Custom Module Development',
    'services.odoo.point4': 'Integration with Other Systems',
    'services.odoo.point5': 'Post-Implementation Support',
    'services.odoo.cta': 'Explore Our Odoo Solutions',

    'services.ai.title': 'Artificial Intelligence: From Data to Strategic Decisions',
    'services.ai.description': 'Unlock the power of your data with our AI solutions. From process automation (RPA) and predictive analysis to intelligent chatbots and computer vision, we create systems that learn, optimize, and generate value.',
    'services.ai.benefits': 'Operational optimization, improved customer experience, new revenue sources, competitive advantage.',
    'services.ai.point1': 'Machine Learning and Deep Learning',
    'services.ai.point2': 'Natural Language Processing (NLP)',
    'services.ai.point3': 'Computer Vision',
    'services.ai.point4': 'Robotic Process Automation (RPA)',
    'services.ai.point5': 'Chatbots and Virtual Assistants',
    'services.ai.point6': 'Virtual Agents and AI Assistants',
    'services.ai.point7': 'Process Automation',
    'services.ai.point8': 'Fully Automated Workflows powered by AI',
    'services.ai.cta': 'Discover Our AI Projects',

    'services.custom.title': 'Custom Software: The Perfect Solution for Unique Challenges',
    'services.custom.description': 'When standard solutions are not enough, we create applications that fit your processes and goals like a glove. From web and mobile applications to complex management systems, we design and develop robust, scalable, and user-centered software.',
    'services.custom.benefits': 'Unmatched efficiency, competitive advantage, total control over your technology, guaranteed security.',
    'services.custom.point1': 'Custom Analysis and Design',
    'services.custom.point2': 'Front-end and Back-end Development',
    'services.custom.point3': 'Mobile Applications (iOS/Android)',
    'services.custom.point4': 'Enterprise Management Systems (CRM, ERP, etc.)',
    'services.custom.point5': 'Legacy System Modernization',
    'services.custom.cta': 'Tell Us Your Idea',

    'services.consulting.title': 'Technological Consultancy: Strategy and Vision for Your Digital Future',
    'services.consulting.description': 'Our team of expert consultants will guide you in defining your technological roadmap. From infrastructure evaluation to selecting the most suitable solutions and project management, we offer a clear and strategic vision.',
    'services.consulting.benefits': 'Risk reduction, investment optimization, planned innovation, technological alignment with business goals.',
    'services.consulting.point1': 'Technological Audit',
    'services.consulting.point2': 'Strategic IT Planning',
    'services.consulting.point3': 'Technology and Vendor Selection',
    'services.consulting.point4': 'Software Project Management',
    'services.consulting.point5': 'Security and Cybersecurity',
    'services.consulting.cta': 'Consult Our Experts',

    'services.keyBenefits': 'Key Benefits:',
    'services.whatWeOffer': 'What We Offer:',
    'services.finalCta.title': 'No matter how complex your challenge is, we have the expertise to turn it into success.',
    'services.finalCta.subtitle': 'Let\'s talk about your next project and discover how we can help you achieve your goals.',
    'services.finalCta.button': 'Contact Us',

    // Solutions Page - Complete content
    'solutions.warehouse.title': 'Warehouse Management System',
    'solutions.warehouse.subtitle': 'Optimize Your Warehouse Operations and Inventory Control',
    'solutions.warehouse.description': 'A Warehouse Management System (WMS) is a comprehensive software solution designed to optimize and automate warehouse operations from receiving to shipping. It provides real-time visibility into inventory levels, locations, and movements while streamlining picking, packing, and shipping processes.',
    'solutions.warehouse.feature1': 'Real-time inventory tracking and location management',
    'solutions.warehouse.feature2': 'Automated picking route optimization',
    'solutions.warehouse.feature3': 'Receiving and put-away management',
    'solutions.warehouse.feature4': 'Order fulfillment and wave planning',
    'solutions.warehouse.feature5': 'Barcode, RFID, and mobile device integration',
    'solutions.warehouse.feature6': 'Warehouse layout optimization and slotting',
    'solutions.warehouse.feature7': 'Labor management and productivity tracking',
    'solutions.warehouse.feature8': 'Shipping and dock management',
    'solutions.warehouse.feature9': 'Cycle counting and inventory accuracy',
    'solutions.warehouse.feature10': 'Integration with ERP, TMS, and e-commerce platforms',
    'solutions.warehouse.benefit1': 'Increase picking productivity by 25-40%',
    'solutions.warehouse.benefit2': 'Improve inventory accuracy to 99.5%+',
    'solutions.warehouse.benefit3': 'Reduce order fulfillment time by 30-50%',
    'solutions.warehouse.benefit4': 'Optimize warehouse space utilization by 20-30%',
    'solutions.warehouse.benefit5': 'Decrease labor costs through automation',
    'solutions.warehouse.benefit6': 'Enhance customer satisfaction with faster deliveries',
    'solutions.warehouse.benefit7': 'Reduce inventory carrying costs',
    'solutions.warehouse.benefit8': 'Minimize picking errors and returns',

    'solutions.delivery.title': 'Delivery Management System',
    'solutions.delivery.subtitle': 'Optimize Your Last-Mile Delivery Operations',
    'solutions.delivery.description': 'A comprehensive Delivery Management System (DMS) designed to streamline and optimize your entire delivery process from dispatch to customer doorstep. Our solution provides real-time tracking, route optimization, driver management, and customer communication tools.',
    'solutions.delivery.feature1': 'Real-time delivery tracking and monitoring',
    'solutions.delivery.feature2': 'Intelligent route optimization and planning',
    'solutions.delivery.feature3': 'Driver mobile app with GPS navigation',
    'solutions.delivery.feature4': 'Automated customer notifications and updates',
    'solutions.delivery.feature5': 'Proof of delivery with digital signatures',
    'solutions.delivery.feature6': 'Fleet management and vehicle tracking',
    'solutions.delivery.feature7': 'Delivery scheduling and time slot management',
    'solutions.delivery.feature8': 'Performance analytics and reporting',
    'solutions.delivery.feature9': 'Integration with e-commerce and ERP systems',
    'solutions.delivery.feature10': 'Customer portal for delivery preferences',
    'solutions.delivery.benefit1': 'Reduce delivery costs by 20-35%',
    'solutions.delivery.benefit2': 'Improve delivery success rate to 95%+',
    'solutions.delivery.benefit3': 'Decrease delivery time by 25-40%',
    'solutions.delivery.benefit4': 'Enhance customer satisfaction scores',
    'solutions.delivery.benefit5': 'Optimize fleet utilization and fuel efficiency',
    'solutions.delivery.benefit6': 'Reduce failed delivery attempts',
    'solutions.delivery.benefit7': 'Increase driver productivity',
    'solutions.delivery.benefit8': 'Provide complete delivery visibility',

    'solutions.services.title': 'Services Solution',
    'solutions.services.subtitle': 'Automate Your Processes and Improve Your Team\'s Productivity',
    'solutions.services.description': 'Tailored solution for service-based businesses that streamlines project management, resource allocation, client management, and billing processes.',
    'solutions.services.feature1': 'Project and task management',
    'solutions.services.feature2': 'Time tracking and billing',
    'solutions.services.feature3': 'Client relationship management',
    'solutions.services.feature4': 'Resource scheduling',
    'solutions.services.feature5': 'Document management',
    'solutions.services.feature6': 'Financial reporting',
    'solutions.services.benefit1': 'Increase team productivity by 40%',
    'solutions.services.benefit2': 'Improve client satisfaction',
    'solutions.services.benefit3': 'Streamline billing processes',
    'solutions.services.benefit4': 'Better project visibility',

    'solutions.keyFeatures': 'Key Features:',
    'solutions.expectedBenefits': 'Expected Benefits:',
    'solutions.learnMore': 'Learn More',
    'solutions.whyChoose.title': 'Why Choose Our Industry Solutions?',
    'solutions.whyChoose.expertise.title': 'Industry Expertise',
    'solutions.whyChoose.expertise.desc': 'Deep understanding of sector-specific challenges and requirements.',
    'solutions.whyChoose.results.title': 'Proven Results',
    'solutions.whyChoose.results.desc': 'Track record of successful implementations across various industries.',
    'solutions.whyChoose.scalable.title': 'Scalable Solutions',
    'solutions.whyChoose.scalable.desc': 'Solutions that grow with your business and adapt to changing needs.',
    'solutions.whyChoose.support.title': 'Comprehensive Support',
    'solutions.whyChoose.support.desc': 'Full lifecycle support from implementation to ongoing maintenance.',
    'solutions.cta.title': 'Ready to Transform Your Business?',
    'solutions.cta.subtitle': 'Discover how our industry-specific solutions can drive efficiency, reduce costs, and accelerate your growth.',
    'solutions.cta.button': 'Get Started Today',

    // Projects Page - Complete content
    'projects.filters.all': 'All Projects',
    'projects.filters.openbravo': 'Openbravo',
    'projects.filters.odoo': 'Odoo',
    'projects.filters.ai': 'AI Solutions',
    'projects.filters.custom': 'Custom Development',
    'projects.keyResults': 'Key Results:',
    'projects.viewCase': 'View Case Study',
    'projects.featured.title': 'Featured Success Story: Halsted Logistics Transformation',
    'projects.featured.challenge': 'The Challenge:',
    'projects.featured.challengeDesc': 'Halsted was struggling with manual inventory processes, leading to stockouts, overstock situations, and delayed deliveries that were affecting customer satisfaction.',
    'projects.featured.solution': 'Our Solution:',
    'projects.featured.solutionDesc': 'We implemented a comprehensive Openbravo ERP system with custom modules for real-time inventory tracking, automated reordering, and integrated logistics management.',
    'projects.featured.results': 'Results Achieved:',
    'projects.featured.costReduction': 'Cost Reduction',
    'projects.featured.fasterDelivery': 'Faster Delivery',
    'projects.cta.title': 'Let\'s Talk About Your Challenge',
    'projects.cta.subtitle': 'We can help you achieve similar results. Every great project starts with a conversation.',
    'projects.cta.button': 'Contact Us Today',

    // About Page - Complete content
    'about.story.content1': 'Since 2015, Doce Leguas has been committed to excellence in software development. Our mission is to empower companies through cutting-edge technology, transforming innovative ideas into digital solutions that drive growth and efficiency.',
    'about.story.content2': 'We started as a small team of passionate developers and have grown into a comprehensive software consultancy, serving clients across various industries with customized solutions that make a real difference.',
    'about.stats.projects': 'Successful Projects',
    'about.stats.experience': 'Years Combined Experience',
    'about.stats.clients': 'Happy Clients',
    'about.stats.satisfaction': 'Client Satisfaction',
    'about.values.excellence.desc': 'We strive for perfection in every line of code and every strategy, delivering solutions that exceed expectations.',
    'about.values.innovation.desc': 'Always exploring new technologies and methodologies to offer cutting-edge solutions that drive competitive advantage.',
    'about.values.integrity.desc': 'We act with honesty and transparency in all our interactions, building trust through consistent ethical behavior.',
    'about.values.customer.desc': 'Your success is our priority and driving force, ensuring every solution aligns with your business goals.',
    'about.values.collaboration.desc': 'We believe in the power of teamwork and synergy with our clients, working together to achieve exceptional results.',
    'about.team.nono.position': 'Lead ERP Architect',
    'about.team.nono.desc': 'Certified Openbravo and Odoo expert with extensive experience in complex ERP implementations across various industries.',
    'about.team.mark.position': 'Lead AI Architect',
    'about.team.mark.desc': 'Specialist in artificial intelligence and machine learning with 10+ years developing intelligent solutions for enterprise clients.',
    'about.team.rafael.position': 'Lead Retail Architect',
    'about.team.rafael.desc': 'Expert in retail solutions and digital transformation with extensive experience optimizing inventory management, and customer experience across retail organizations.',
    'about.team.maarten.position': 'Supply Chain Consultant',
    'about.team.maarten.desc': 'Expert in supply chain optimization and logistics management with deep knowledge of warehouse operations, distribution networks, and inventory control systems.',
    'about.culture.content1': 'At Doce Leguas, we foster a culture of continuous learning, innovation, and collaboration. Our team is passionate about technology and committed to staying at the forefront of industry trends.',
    'about.culture.content2': 'We believe in work-life balance, professional development, and creating an environment where creativity and technical excellence thrive. This culture directly translates into better solutions for our clients.',
    'about.culture.item1': 'Continuous Learning',
    'about.culture.item2': 'Innovation Focus',
    'about.culture.item3': 'Team Collaboration',
    'about.culture.item4': 'Client Partnership',

    // Projects Page - Complete content
    'projects.halsted.title': 'Halsted Logistics Optimization',
    'projects.halsted.desc': 'Complete Openbravo ERP implementation with custom modules for inventory management, resulting in 30% reduction in operational costs and 25% improvement in delivery times.',
    'projects.halsted.sector': 'Retail & Logistics',
    'projects.halsted.result1': '30% cost reduction',
    'projects.halsted.result2': '25% faster delivery',
    'projects.halsted.result3': '95% inventory accuracy',
    'projects.halsted.testimonial': 'Thanks to Doce Leguas, our operations have drastically improved. Their professionalism and knowledge are exceptional.',
    'projects.halsted.client': 'Brian, Operations Manager at Halsted',

    'projects.ai.title': 'AI-Powered Predictive Analytics',
    'projects.ai.desc': 'Development of machine learning models for demand forecasting and predictive maintenance, enabling data-driven decision making and 40% improvement in operational efficiency.',
    'projects.ai.sector': 'Manufacturing',
    'projects.ai.result1': '40% efficiency gain',
    'projects.ai.result2': '60% better forecasting',
    'projects.ai.result3': '$2M cost savings',
    'projects.ai.testimonial': 'The AI solution they implemented exceeded all our expectations. The predictive capabilities have transformed our planning process.',
    'projects.ai.client': 'Maria Rodriguez, CTO at TechCorp Solutions',

    'projects.custom.title': 'Custom ERP Development',
    'projects.custom.desc': 'Built from scratch a comprehensive ERP system tailored specifically for a growing services company, integrating project management, billing, and resource planning.',
    'projects.custom.sector': 'Professional Services',
    'projects.custom.result1': '45% productivity increase',
    'projects.custom.result2': '99.9% uptime',
    'projects.custom.result3': '100% custom fit',
    'projects.custom.testimonial': 'Finally, a system that works exactly how we do business. The custom ERP has streamlined all our processes.',
    'projects.custom.client': 'James Wilson, CEO at ProServ Consulting',

    'projects.odoo.title': 'Odoo Multi-Company Implementation',
    'projects.odoo.desc': 'Comprehensive Odoo deployment across multiple subsidiaries with custom modules for consolidated reporting, inter-company transactions, and unified workflow management.',
    'projects.odoo.sector': 'Finance & Holding',
    'projects.odoo.result1': '5 companies unified',
    'projects.odoo.result2': '50% faster reporting',
    'projects.odoo.result3': '80% process automation',
    'projects.odoo.testimonial': 'The Odoo implementation has given us complete visibility across all our companies. Outstanding work.',
    'projects.odoo.client': 'Sarah Chen, CFO at GlobalTech Holdings',

    'projects.warehouse.title': 'Smart Warehouse Management',
    'projects.warehouse.desc': 'AI-enhanced warehouse management system with computer vision for inventory tracking, automated reordering, and predictive maintenance of equipment.',
    'projects.warehouse.sector': 'Logistics & Distribution',
    'projects.warehouse.result1': '35% faster processing',
    'projects.warehouse.result2': '99% inventory accuracy',
    'projects.warehouse.result3': '20% cost reduction',
    'projects.warehouse.testimonial': 'The computer vision system has revolutionized our warehouse operations. Incredible accuracy and efficiency.',
    'projects.warehouse.client': 'Mike Torres, Warehouse Director at LogiFlow',

    'projects.cloud.title': 'Cloud Migration & Modernization',
    'projects.cloud.desc': 'Complete legacy system modernization with cloud migration, API development, and mobile application creation for a traditional manufacturing company.',
    'projects.cloud.sector': 'Manufacturing',
    'projects.cloud.result1': '70% performance boost',
    'projects.cloud.result2': '24/7 availability',
    'projects.cloud.result3': 'Modern mobile access',
    'projects.cloud.testimonial': 'They brought our 20-year-old system into the modern age. The transformation is remarkable.',
    'projects.cloud.client': 'Robert Kim, IT Director at SteelWorks Inc',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.solutions': 'Soluciones',
    'nav.projects': 'Proyectos',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.getStarted': 'Comenzar',

    // Home Page
    'home.hero.title': 'Transforma Tu Negocio con Soluciones de Software Innovadoras',
    'home.hero.subtitle': 'Nos especializamos en Openbravo, Odoo, soluciones de IA y desarrollo personalizado para impulsar tu transformación digital.',
    'home.hero.viewServices': 'Ver Nuestros Servicios',
    'home.hero.startProject': 'Iniciar Tu Proyecto',

    'home.valueProps.title': '¿Por Qué Elegir Doce Leguas?',
    'home.valueProps.subtitle': 'Combinamos experiencia técnica con visión estratégica para entregar soluciones que realmente marcan la diferencia.',
    'home.valueProps.innovation': 'Innovación',
    'home.valueProps.innovation.desc': 'Nos mantenemos a la vanguardia de la tecnología para ofrecer soluciones de última generación.',
    'home.valueProps.custom': 'Personalización',
    'home.valueProps.custom.desc': 'Cada solución se adapta a tus necesidades específicas y procesos de negocio.',
    'home.valueProps.results': 'Resultados Comprobados',
    'home.valueProps.results.desc': 'Nuestro historial habla por sí mismo con implementaciones exitosas.',
    'home.valueProps.team': 'Equipo Experto',
    'home.valueProps.team.desc': 'Profesionales certificados con años de experiencia en soluciones empresariales.',

    'home.services.title': 'Nuestros Servicios Principales',
    'home.services.subtitle': 'Soluciones integrales para transformar las operaciones de tu negocio.',
    'home.services.openbravo': 'Openbravo ERP',
    'home.services.openbravo.desc': 'Implementación y personalización completa de ERP para gestión empresarial.',
    'home.services.odoo': 'Soluciones Odoo',
    'home.services.odoo.desc': 'Gestión empresarial integral con la suite integrada de Odoo.',
    'home.services.ai': 'Soluciones de IA',
    'home.services.ai.desc': 'Automatización inteligente, agentes virtuales y flujos de trabajo potenciados por IA para toma de decisiones basada en datos.',
    'home.services.custom': 'Desarrollo Personalizado',
    'home.services.custom.desc': 'Soluciones de software a medida construidas específicamente para tus necesidades.',
    'home.services.n8n': 'Automatización n8n',
    'home.services.n8n.desc': 'Automatización de flujos de trabajo e integración de sistemas con n8n.',
    'home.services.automation': 'Automatización de Procesos',
    'home.services.automation.desc': 'Optimiza operaciones con soluciones de automatización inteligente.',
    'home.services.learnMore': 'Saber Más',

    'home.projects.title': 'Historias de Éxito',
    'home.projects.subtitle': 'Descubre cómo hemos ayudado a empresas a lograr sus objetivos de transformación digital.',
    'home.projects.viewCase': 'Ver Caso de Estudio',

    'home.testimonials.title': 'Lo Que Dicen Nuestros Clientes',

    'home.logistics.title': 'Soluciones Especializadas para Logística y Retail',
    'home.logistics.subtitle': 'Experiencia específica de la industria para optimizar tus operaciones e impulsar el crecimiento.',
    'home.logistics.supply.title': 'Optimización de Cadena de Suministro',
    'home.logistics.supply.desc': 'Optimiza tus operaciones logísticas con gestión inteligente de cadena de suministro.',
    'home.logistics.supply.feature1': 'Seguimiento de inventario en tiempo real',
    'home.logistics.supply.feature2': 'Sistemas de reorden automatizado',
    'home.logistics.supply.feature3': 'Planificación predictiva de demanda',
    'home.logistics.retail.title': 'Gestión de Retail',
    'home.logistics.retail.desc': 'Soluciones completas de retail desde POS hasta gestión de clientes.',
    'home.logistics.retail.feature1': 'Sistemas POS integrados',
    'home.logistics.retail.feature2': 'Programas de fidelización',
    'home.logistics.retail.feature3': 'Integración multicanal',
    'home.logistics.expertise.title': 'Experiencia en la Industria',
    'home.logistics.expertise.desc': 'Comprensión profunda de los desafíos de logística y retail.',
    'home.logistics.expertise.stat1': 'Proyectos',
    'home.logistics.expertise.stat2': 'Tasa de Éxito',
    'home.logistics.cta': 'Explorar Nuestras Soluciones',

    'home.cta.title': '¿Listo para Transformar Tu Negocio?',
    'home.cta.subtitle': 'Hablemos sobre cómo podemos ayudarte a lograr tus objetivos de transformación digital.',
    'home.cta.schedule': 'Programar una Consulta',
    'home.cta.contact': 'Contáctanos',

    // About Page
    'about.title': 'Acerca de Doce Leguas: Innovación, Excelencia y Resultados',
    'about.subtitle': 'Somos un equipo de profesionales apasionados dedicados a transformar empresas a través de soluciones tecnológicas innovadoras.',
    'about.story.title': 'Nuestra Historia',
    'about.vision.title': 'Nuestra Visión',
    'about.vision.desc': 'Ser el referente en soluciones de software personalizadas, reconocidos por nuestra capacidad de innovar, la calidad de nuestro trabajo y el éxito sostenido de nuestros clientes.',
    'about.values.title': 'Nuestros Valores',
    'about.values.subtitle': 'Los principios que guían todo lo que hacemos.',
    'about.values.excellence': 'Excelencia',
    'about.values.innovation': 'Innovación',
    'about.values.integrity': 'Integridad',
    'about.values.customer': 'Enfoque al Cliente',
    'about.values.collaboration': 'Colaboración',
    'about.team.title': 'Conoce Nuestro Equipo',
    'about.team.subtitle': 'Profesionales experimentados comprometidos con tu éxito.',
    'about.culture.title': 'Nuestra Cultura Empresarial',
    'about.cta.title': '¿Listo para Trabajar Juntos?',
    'about.cta.subtitle': 'Hablemos sobre cómo nuestro equipo puede ayudarte a lograr tus objetivos empresariales.',
    'about.cta.contact': 'Contactar Nuestro Equipo',

    // Detalles de miembros del equipo
    'about.team.nono.position': 'Arquitecto ERP Principal',
    'about.team.nono.description': 'Experto certificado en Openbravo y Odoo con amplia experiencia en implementaciones complejas de ERP en diversas industrias.',
    'about.team.mark.position': 'Arquitecto de IA Principal',
    'about.team.mark.description': 'Especialista en inteligencia artificial y aprendizaje automático con más de 10 años desarrollando soluciones inteligentes para clientes empresariales.',
    'about.team.rafael.position': 'Arquitecto Retail Principal', 
    'about.team.rafael.description': 'Experto en soluciones retail y transformación digital con amplia experiencia optimizando gestión de inventarios y experiencia del cliente en organizaciones retail.',
    'about.team.maarten.position': 'Consultor de Cadena de Suministro',
    'about.team.maarten.description': 'Experto en optimización de cadena de suministro y gestión logística con profundo conocimiento de operaciones de almacén, redes de distribución y sistemas de control de inventario.',

    // Contact Page
    'contact.title': 'Contáctanos: Comencemos Tu Transformación Digital',
    'contact.subtitle': 'Estamos aquí para ayudarte a lograr tus objetivos empresariales. Ponte en contacto con nuestro equipo de expertos.',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.fullName': 'Nombre Completo',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.company': 'Empresa',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.form.success': '¡Mensaje Enviado Exitosamente!',
    'contact.form.successDesc': 'Gracias por contactarnos. Te responderemos dentro de 24 horas.',
    'contact.info.title': 'Información de Contacto',
    'contact.info.email': 'Correo',
    'contact.info.emailDesc': 'Envíanos un correo en cualquier momento',
    'contact.info.phone': 'Teléfono',
    'contact.info.phoneDesc': 'Llámanos durante horario comercial',
    'contact.info.office': 'Oficina',
    'contact.info.officeDesc': 'Visita nuestra oficina',
    'contact.info.hours': 'Horario Comercial',
    'contact.info.hoursDesc': '9:00 AM - 6:00 PM',

    // Footer
    'footer.description': 'Transformando empresas a través de soluciones de software innovadoras y consultoría experta.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Servicios',
    'footer.contactInfo': 'Información de Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.legal': 'Aviso Legal',
    'footer.sitemap': 'Mapa del Sitio',

    // ChatBot
    'chatbot.title': 'Asistente Doce Leguas',
    'chatbot.subtitle': '¿Cómo podemos ayudarte?',
    'chatbot.welcome': '¡Hola! Estoy aquí para ayudarte con cualquier pregunta sobre nuestros servicios. ¿Cómo puedo asistirte hoy?',
    'chatbot.placeholder': 'Escribe tu mensaje...',
    'chatbot.open': 'Abrir chat',
    'chatbot.close': 'Cerrar chat',
    'chatbot.defaultResponse': 'Gracias por tu mensaje. Nuestro equipo te responderá pronto.',
    'chatbot.errorMessage': 'Lo siento, tengo problemas de conexión ahora. Por favor intenta más tarde o contáctanos directamente.',

    // Services Page
    'services.title': 'Nuestros Servicios: Tu Camino hacia la Excelencia Digital',
    'services.subtitle': 'En Doce Leguas, combinamos profunda experiencia técnica con visión estratégica empresarial para ofrecerte soluciones de software que realmente funcionan. Explora nuestra gama de servicios diseñados para impulsar tu crecimiento.',

    // Solutions Page
    'solutions.title': 'Soluciones Integrales para Tu Sector',
    'solutions.subtitle': 'Hemos desarrollado soluciones empaquetadas que abordan los desafíos más comunes en diversas industrias, combinando nuestra experiencia en Openbravo, Odoo, IA y desarrollo personalizado para ofrecerte un valor sin precedentes.',

    // Projects Page
    'projects.title': 'Nuestros Proyectos: Historias de Éxito y Transformación',
    'projects.subtitle': 'Cada proyecto es una oportunidad para demostrar nuestro compromiso con la excelencia. Aquí presentamos algunos de nuestros trabajos más relevantes, mostrando cómo hemos ayudado a empresas a lograr sus objetivos digitales.',

    // Services Page - Complete content in Spanish
    'services.openbravo.title': 'Transforma tu Gestión con Openbravo: Eficiencia y Control Total',
    'services.openbravo.description': 'Como expertos en Openbravo, ofrecemos desde la implementación inicial hasta la personalización avanzada y el soporte continuo. Maximizamos el potencial de tu ERP para optimizar tus operaciones, desde finanzas y ventas hasta logística y producción.',
    'services.openbravo.benefits': 'Costos operativos reducidos, mejor toma de decisiones, escalabilidad garantizada, integración perfecta.',
    'services.openbravo.point1': 'Implementación y Migración',
    'services.openbravo.point2': 'Personalización y Desarrollo de Módulos',
    'services.openbravo.point3': 'Soporte y Mantenimiento',
    'services.openbravo.point4': 'Capacitación de Usuarios',
    'services.openbravo.cta': 'Conoce Más sobre Openbravo',

    'services.odoo.title': 'Odoo: Centraliza y Automatiza tu Negocio con Nuestra Experiencia',
    'services.odoo.description': 'Odoo es la suite definitiva de aplicaciones empresariales. Te ayudamos a explotar todo su potencial, adaptando módulos como CRM, contabilidad, gestión de proyectos, e-commerce y más a tus flujos de trabajo específicos.',
    'services.odoo.benefits': 'Mayor productividad, visión 360° del negocio, reducción de errores manuales, escalabilidad y flexibilidad.',
    'services.odoo.point1': 'Consultoría y Análisis de Requerimientos',
    'services.odoo.point2': 'Implementación y Configuración',
    'services.odoo.point3': 'Desarrollo de Módulos Personalizados',
    'services.odoo.point4': 'Integración con Otros Sistemas',
    'services.odoo.point5': 'Soporte Post-Implementación',
    'services.odoo.cta': 'Explora Nuestras Soluciones Odoo',

    'services.ai.title': 'Inteligencia Artificial: De los Datos a las Decisiones Estratégicas',
    'services.ai.description': 'Desbloquea el poder de tus datos con nuestras soluciones de IA. Desde automatización de procesos (RPA) y análisis predictivo hasta chatbots inteligentes y visión por computadora, creamos sistemas que aprenden, optimizan y generan valor.',
    'services.ai.benefits': 'Optimización operacional, mejor experiencia del cliente, nuevas fuentes de ingresos, ventaja competitiva.',
    'services.ai.point1': 'Machine Learning y Deep Learning',
    'services.ai.point2': 'Procesamiento de Lenguaje Natural (NLP)',
    'services.ai.point3': 'Visión por Computadora',
    'services.ai.point4': 'Automatización Robótica de Procesos (RPA)',
    'services.ai.point5': 'Chatbots y Asistentes Virtuales',
    'services.ai.point6': 'Agentes Virtuales y Asistentes de IA',
    'services.ai.point7': 'Automatización de Procesos',
    'services.ai.point8': 'Flujos de Trabajo Completamente Automatizados con IA',
    'services.ai.cta': 'Descubre Nuestros Proyectos de IA',

    'services.custom.title': 'Software Personalizado: La Solución Perfecta para Desafíos Únicos',
    'services.custom.description': 'Cuando las soluciones estándar no son suficientes, creamos aplicaciones que se ajustan a tus procesos y objetivos como un guante. Desde aplicaciones web y móviles hasta sistemas de gestión complejos, diseñamos y desarrollamos software robusto, escalable y centrado en el usuario.',
    'services.custom.benefits': 'Eficiencia inigualable, ventaja competitiva, control total sobre tu tecnología, seguridad garantizada.',
    'services.custom.point1': 'Análisis y Diseño Personalizado',
    'services.custom.point2': 'Desarrollo Front-end y Back-end',
    'services.custom.point3': 'Aplicaciones Móviles (iOS/Android)',
    'services.custom.point4': 'Sistemas de Gestión Empresarial (CRM, ERP, etc.)',
    'services.custom.point5': 'Modernización de Sistemas Legacy',
    'services.custom.cta': 'Cuéntanos Tu Idea',

    'services.consulting.title': 'Consultoría Tecnológica: Estrategia y Visión para tu Futuro Digital',
    'services.consulting.description': 'Nuestro equipo de consultores expertos te guiará en la definición de tu hoja de ruta tecnológica. Desde evaluación de infraestructura hasta selección de las soluciones más adecuadas y gestión de proyectos, ofrecemos una visión clara y estratégica.',
    'services.consulting.benefits': 'Reducción de riesgos, optimización de inversiones, innovación planificada, alineación tecnológica con objetivos empresariales.',
    'services.consulting.point1': 'Auditoría Tecnológica',
    'services.consulting.point2': 'Planificación Estratégica de TI',
    'services.consulting.point3': 'Selección de Tecnologías y Proveedores',
    'services.consulting.point4': 'Gestión de Proyectos de Software',
    'services.consulting.point5': 'Seguridad y Ciberseguridad',
    'services.consulting.cta': 'Consulta a Nuestros Expertos',

    'services.keyBenefits': 'Beneficios Clave:',
    'services.whatWeOffer': 'Lo Que Ofrecemos:',
    'services.finalCta.title': 'No importa qué tan complejo sea tu desafío, tenemos la experiencia para convertirlo en éxito.',
    'services.finalCta.subtitle': 'Hablemos sobre tu próximo proyecto y descubre cómo podemos ayudarte a lograr tus objetivos.',
    'services.finalCta.button': 'Contáctanos',

    // Solutions Page - Complete content in Spanish
    'solutions.warehouse.title': 'Sistema de Gestión de Almacén',
    'solutions.warehouse.subtitle': 'Optimiza las Operaciones de tu Almacén y Control de Inventario',
    'solutions.warehouse.description': 'Un Sistema de Gestión de Almacén (WMS) es una solución de software integral diseñada para optimizar y automatizar las operaciones de almacén desde la recepción hasta el envío. Proporciona visibilidad en tiempo real de los niveles, ubicaciones y movimientos de inventario.',
    'solutions.warehouse.feature1': 'Seguimiento de inventario y gestión de ubicaciones en tiempo real',
    'solutions.warehouse.feature2': 'Optimización automatizada de rutas de picking',
    'solutions.warehouse.feature3': 'Gestión de recepción y almacenamiento',
    'solutions.warehouse.feature4': 'Cumplimiento de pedidos y planificación de olas',
    'solutions.warehouse.feature5': 'Integración de códigos de barras, RFID y dispositivos móviles',
    'solutions.warehouse.feature6': 'Optimización del diseño del almacén y slotting',
    'solutions.warehouse.feature7': 'Gestión laboral y seguimiento de productividad',
    'solutions.warehouse.feature8': 'Gestión de envíos y muelles',
    'solutions.warehouse.feature9': 'Conteo cíclico y precisión de inventario',
    'solutions.warehouse.feature10': 'Integración con ERP, TMS y plataformas de e-commerce',
    'solutions.warehouse.benefit1': 'Aumentar la productividad de picking en 25-40%',
    'solutions.warehouse.benefit2': 'Mejorar la precisión del inventario a 99.5%+',
    'solutions.warehouse.benefit3': 'Reducir el tiempo de cumplimiento de pedidos en 30-50%',
    'solutions.warehouse.benefit4': 'Optimizar la utilización del espacio del almacén en 20-30%',
    'solutions.warehouse.benefit5': 'Disminuir los costos laborales mediante automatización',
    'solutions.warehouse.benefit6': 'Mejorar la satisfacción del cliente con entregas más rápidas',
    'solutions.warehouse.benefit7': 'Reducir los costos de mantenimiento de inventario',
    'solutions.warehouse.benefit8': 'Minimizar errores de picking y devoluciones',

    'solutions.delivery.title': 'Sistema de Gestión de Entregas',
    'solutions.delivery.subtitle': 'Optimiza tus Operaciones de Entrega de Última Milla',
    'solutions.delivery.description': 'Un Sistema de Gestión de Entregas (DMS) integral diseñado para optimizar todo tu proceso de entrega desde el despacho hasta la puerta del cliente. Nuestra solución proporciona seguimiento en tiempo real, optimización de rutas y herramientas de comunicación con el cliente.',
    'solutions.delivery.feature1': 'Seguimiento y monitoreo de entregas en tiempo real',
    'solutions.delivery.feature2': 'Optimización y planificación inteligente de rutas',
    'solutions.delivery.feature3': 'App móvil para conductores con navegación GPS',
    'solutions.delivery.feature4': 'Notificaciones automáticas y actualizaciones al cliente',
    'solutions.delivery.feature5': 'Prueba de entrega con firmas digitales',
    'solutions.delivery.feature6': 'Gestión de flota y seguimiento de vehículos',
    'solutions.delivery.feature7': 'Programación de entregas y gestión de franjas horarias',
    'solutions.delivery.feature8': 'Análisis de rendimiento y reportes',
    'solutions.delivery.feature9': 'Integración con sistemas de e-commerce y ERP',
    'solutions.delivery.feature10': 'Portal del cliente para preferencias de entrega',
    'solutions.delivery.benefit1': 'Reducir costos de entrega en 20-35%',
    'solutions.delivery.benefit2': 'Mejorar la tasa de éxito de entregas a 95%+',
    'solutions.delivery.benefit3': 'Disminuir el tiempo de entrega en 25-40%',
    'solutions.delivery.benefit4': 'Mejorar las puntuaciones de satisfacción del cliente',
    'solutions.delivery.benefit5': 'Optimizar la utilización de la flota y eficiencia de combustible',
    'solutions.delivery.benefit6': 'Reducir intentos de entrega fallidos',
    'solutions.delivery.benefit7': 'Aumentar la productividad del conductor',
    'solutions.delivery.benefit8': 'Proporcionar visibilidad completa de entregas',

    'solutions.services.title': 'Solución de Servicios',
    'solutions.services.subtitle': 'Automatiza tus Procesos y Mejora la Productividad de tu Equipo',
    'solutions.services.description': 'Solución personalizada para empresas basadas en servicios que optimiza la gestión de proyectos, asignación de recursos, gestión de clientes y procesos de facturación.',
    'solutions.services.feature1': 'Gestión de proyectos y tareas',
    'solutions.services.feature2': 'Seguimiento de tiempo y facturación',
    'solutions.services.feature3': 'Gestión de relaciones con clientes',
    'solutions.services.feature4': 'Programación de recursos',
    'solutions.services.feature5': 'Gestión de documentos',
    'solutions.services.feature6': 'Reportes financieros',
    'solutions.services.benefit1': 'Aumentar la productividad del equipo en 40%',
    'solutions.services.benefit2': 'Mejorar la satisfacción del cliente',
    'solutions.services.benefit3': 'Optimizar procesos de facturación',
    'solutions.services.benefit4': 'Mejor visibilidad de proyectos',

    'solutions.keyFeatures': 'Características Clave:',
    'solutions.expectedBenefits': 'Beneficios Esperados:',
    'solutions.learnMore': 'Conoce Más',
    'solutions.whyChoose.title': '¿Por Qué Elegir Nuestras Soluciones Industriales?',
    'solutions.whyChoose.expertise.title': 'Experiencia en la Industria',
    'solutions.whyChoose.expertise.desc': 'Comprensión profunda de los desafíos y requisitos específicos del sector.',
    'solutions.whyChoose.results.title': 'Resultados Comprobados',
    'solutions.whyChoose.results.desc': 'Historial de implementaciones exitosas en diversas industrias.',
    'solutions.whyChoose.scalable.title': 'Soluciones Escalables',
    'solutions.whyChoose.scalable.desc': 'Soluciones que crecen con tu negocio y se adaptan a las necesidades cambiantes.',
    'solutions.whyChoose.support.title': 'Soporte Integral',
    'solutions.whyChoose.support.desc': 'Soporte completo del ciclo de vida desde implementación hasta mantenimiento continuo.',
    'solutions.cta.title': '¿Listo para Transformar tu Negocio?',
    'solutions.cta.subtitle': 'Descubre cómo nuestras soluciones específicas de la industria pueden impulsar la eficiencia, reducir costos y acelerar tu crecimiento.',
    'solutions.cta.button': 'Comienza Hoy',

    // Projects Page - Complete content in Spanish
    'projects.filters.all': 'Todos los Proyectos',
    'projects.filters.openbravo': 'Openbravo',
    'projects.filters.odoo': 'Odoo',
    'projects.filters.ai': 'Soluciones de IA',
    'projects.filters.custom': 'Desarrollo Personalizado',
    'projects.keyResults': 'Resultados Clave:',
    'projects.viewCase': 'Ver Caso de Estudio',
    'projects.featured.title': 'Historia de Éxito Destacada: Transformación Logística de Halsted',
    'projects.featured.challenge': 'El Desafío:',
    'projects.featured.challengeDesc': 'Halsted luchaba con procesos manuales de inventario, lo que llevaba a desabastecimientos, situaciones de exceso de stock y entregas retrasadas que afectaban la satisfacción del cliente.',
    'projects.featured.solution': 'Nuestra Solución:',
    'projects.featured.solutionDesc': 'Implementamos un sistema ERP Openbravo integral con módulos personalizados para seguimiento de inventario en tiempo real, reorden automatizado y gestión logística integrada.',
    'projects.featured.results': 'Resultados Logrados:',
    'projects.featured.costReduction': 'Reducción de Costos',
    'projects.featured.fasterDelivery': 'Entrega Más Rápida',
    'projects.cta.title': 'Hablemos Sobre Tu Desafío',
    'projects.cta.subtitle': 'Podemos ayudarte a lograr resultados similares. Cada gran proyecto comienza con una conversación.',
    'projects.cta.button': 'Contáctanos Hoy',

    // About Page - Complete content in Spanish
    'about.story.content1': 'Desde 2015, Doce Leguas se ha comprometido con la excelencia en el desarrollo de software. Nuestra misión es empoderar a las empresas a través de tecnología de vanguardia, transformando ideas innovadoras en soluciones digitales que impulsan el crecimiento y la eficiencia.',
    'about.story.content2': 'Comenzamos como un pequeño equipo de desarrolladores apasionados y hemos crecido hasta convertirnos en una consultoría de software integral, sirviendo a clientes de diversas industrias con soluciones personalizadas que marcan una diferencia real.',
    'about.stats.projects': 'Proyectos Exitosos',
    'about.stats.experience': 'Años de Experiencia Combinada',
    'about.stats.clients': 'Clientes Satisfechos',
    'about.stats.satisfaction': 'Satisfacción del Cliente',
    'about.values.excellence.desc': 'Nos esforzamos por la perfección en cada línea de código y cada estrategia, entregando soluciones que superan las expectativas.',
    'about.values.innovation.desc': 'Siempre explorando nuevas tecnologías y metodologías para ofrecer soluciones de vanguardia que impulsen la ventaja competitiva.',
    'about.values.integrity.desc': 'Actuamos con honestidad y transparencia en todas nuestras interacciones, construyendo confianza a través de un comportamiento ético consistente.',
    'about.values.customer.desc': 'Tu éxito es nuestra prioridad y fuerza motriz, asegurando que cada solución se alinee con tus objetivos empresariales.',
    'about.values.collaboration.desc': 'Creemos en el poder del trabajo en equipo y la sinergia con nuestros clientes, trabajando juntos para lograr resultados excepcionales.',
    'about.team.nono.position': 'Arquitecto ERP Principal',
    'about.team.nono.desc': 'Experto certificado en Openbravo y Odoo con amplia experiencia en implementaciones complejas de ERP en diversas industrias.',
    'about.team.mark.position': 'Arquitecto de IA Principal',
    'about.team.mark.desc': 'Especialista en inteligencia artificial y aprendizaje automático con más de 10 años desarrollando soluciones inteligentes para clientes empresariales.',
    'about.team.rafael.position': 'Arquitecto de Retail Principal',
    'about.team.rafael.desc': 'Experto en soluciones de retail y transformación digital con amplia experiencia optimizando la gestión de inventarios y la experiencia del cliente en organizaciones de retail.',
    'about.team.maarten.position': 'Consultor de Cadena de Suministro',
    'about.team.maarten.desc': 'Experto en optimización de cadena de suministro y gestión logística con profundo conocimiento de operaciones de almacén, redes de distribución y sistemas de control de inventario.',
    'about.culture.content1': 'En Doce Leguas, fomentamos una cultura de aprendizaje continuo, innovación y colaboración. Nuestro equipo es apasionado por la tecnología y está comprometido a mantenerse a la vanguardia de las tendencias de la industria.',
    'about.culture.content2': 'Creemos en el equilibrio trabajo-vida, el desarrollo profesional y la creación de un ambiente donde la creatividad y la excelencia técnica prosperen. Esta cultura se traduce directamente en mejores soluciones para nuestros clientes.',
    'about.culture.item1': 'Aprendizaje Continuo',
    'about.culture.item2': 'Enfoque en Innovación',
    'about.culture.item3': 'Colaboración en Equipo',
    'about.culture.item4': 'Asociación con Clientes',

    // Projects Page - Complete content in Spanish
    'projects.halsted.title': 'Optimización Logística de Halsted',
    'projects.halsted.desc': 'Implementación completa de ERP Openbravo con módulos personalizados para gestión de inventario, resultando en 30% de reducción en costos operativos y 25% de mejora en tiempos de entrega.',
    'projects.halsted.sector': 'Retail y Logística',
    'projects.halsted.result1': '30% reducción de costos',
    'projects.halsted.result2': '25% entrega más rápida',
    'projects.halsted.result3': '95% precisión de inventario',
    'projects.halsted.testimonial': 'Gracias a Doce Leguas, nuestras operaciones han mejorado drásticamente. Su profesionalismo y conocimiento son excepcionales.',
    'projects.halsted.client': 'Brian, Gerente de Operaciones en Halsted',

    'projects.ai.title': 'Análisis Predictivo Potenciado por IA',
    'projects.ai.desc': 'Desarrollo de modelos de aprendizaje automático para pronóstico de demanda y mantenimiento predictivo, habilitando toma de decisiones basada en datos y 40% de mejora en eficiencia operacional.',
    'projects.ai.sector': 'Manufactura',
    'projects.ai.result1': '40% ganancia en eficiencia',
    'projects.ai.result2': '60% mejor pronóstico',
    'projects.ai.result3': '$2M ahorro en costos',
    'projects.ai.testimonial': 'La solución de IA que implementaron superó todas nuestras expectativas. Las capacidades predictivas han transformado nuestro proceso de planificación.',
    'projects.ai.client': 'Maria Rodriguez, CTO en TechCorp Solutions',

    'projects.custom.title': 'Desarrollo de ERP Personalizado',
    'projects.custom.desc': 'Construido desde cero un sistema ERP integral adaptado específicamente para una empresa de servicios en crecimiento, integrando gestión de proyectos, facturación y planificación de recursos.',
    'projects.custom.sector': 'Servicios Profesionales',
    'projects.custom.result1': '45% aumento de productividad',
    'projects.custom.result2': '99.9% tiempo de actividad',
    'projects.custom.result3': '100% ajuste personalizado',
    'projects.custom.testimonial': 'Finalmente, un sistema que funciona exactamente como hacemos negocios. El ERP personalizado ha optimizado todos nuestros procesos.',
    'projects.custom.client': 'James Wilson, CEO en ProServ Consulting',

    'projects.odoo.title': 'Implementación Multi-Empresa de Odoo',
    'projects.odoo.desc': 'Despliegue integral de Odoo en múltiples subsidiarias con módulos personalizados para reportes consolidados, transacciones inter-empresas y gestión unificada de flujos de trabajo.',
    'projects.odoo.sector': 'Finanzas y Holding',
    'projects.odoo.result1': '5 empresas unificadas',
    'projects.odoo.result2': '50% reportes más rápidos',
    'projects.odoo.result3': '80% automatización de procesos',
    'projects.odoo.testimonial': 'La implementación de Odoo nos ha dado visibilidad completa en todas nuestras empresas. Trabajo excepcional.',
    'projects.odoo.client': 'Sarah Chen, CFO en GlobalTech Holdings',

    'projects.warehouse.title': 'Gestión Inteligente de Almacén',
    'projects.warehouse.desc': 'Sistema de gestión de almacén mejorado con IA con visión por computadora para seguimiento de inventario, reorden automatizado y mantenimiento predictivo de equipos.',
    'projects.warehouse.sector': 'Logística y Distribución',
    'projects.warehouse.result1': '35% procesamiento más rápido',
    'projects.warehouse.result2': '99% precisión de inventario',
    'projects.warehouse.result3': '20% reducción de costos',
    'projects.warehouse.testimonial': 'El sistema de visión por computadora ha revolucionado nuestras operaciones de almacén. Precisión y eficiencia increíbles.',
    'projects.warehouse.client': 'Mike Torres, Director de Almacén en LogiFlow',

    'projects.cloud.title': 'Migración a la Nube y Modernización',
    'projects.cloud.desc': 'Modernización completa del sistema legacy con migración a la nube, desarrollo de API y creación de aplicación móvil para una empresa manufacturera tradicional.',
    'projects.cloud.sector': 'Manufactura',
    'projects.cloud.result1': '70% mejora en rendimiento',
    'projects.cloud.result2': 'Disponibilidad 24/7',
    'projects.cloud.result3': 'Acceso móvil moderno',
    'projects.cloud.testimonial': 'Trajeron nuestro sistema de 20 años a la era moderna. La transformación es notable.',
    'projects.cloud.client': 'Robert Kim, Director de TI en SteelWorks Inc',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};