import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.solutions': 'Solutions',
    'nav.projects': 'Projects',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',

    // Home Page
    'home.hero.title': 'Transform Your Business with Innovative Technology Solutions',
    'home.hero.subtitle': 'We specialize in Openbravo ERP, Odoo, AI solutions, and custom development to optimize your business processes and drive growth.',
    'home.hero.viewServices': 'View Our Services',
    'home.hero.startProject': 'Start Your Project',

    'home.valueProps.title': 'Why Choose Doce Leguas?',
    'home.valueProps.subtitle': 'We combine technical expertise with business understanding to deliver solutions that truly transform your operations.',
    'home.valueProps.innovation': 'Innovation',
    'home.valueProps.innovation.desc': 'We stay at the forefront of technology to provide cutting-edge solutions.',
    'home.valueProps.custom': 'Customization',
    'home.valueProps.custom.desc': 'Every solution is tailored to your specific business needs and goals.',
    'home.valueProps.results': 'Results',
    'home.valueProps.results.desc': 'We focus on measurable outcomes that drive real business value.',
    'home.valueProps.team': 'Expert Team',
    'home.valueProps.team.desc': 'Our experienced professionals bring deep expertise in enterprise solutions.',

    'home.services.title': 'Our Core Services',
    'home.services.subtitle': 'Comprehensive technology solutions designed to accelerate your business growth.',
    'home.services.openbravo': 'Openbravo ERP',
    'home.services.openbravo.desc': 'Complete ERP implementation and customization for enterprise resource planning.',
    'home.services.odoo': 'Odoo Solutions',
    'home.services.odoo.desc': 'Comprehensive business management with Odoo\'s integrated suite of applications.',
    'home.services.ai': 'AI Solutions',
    'home.services.ai.desc': 'Intelligent automation and data analytics to optimize your business processes.',
    'home.services.custom': 'Custom Development',
    'home.services.custom.desc': 'Bespoke software solutions built specifically for your unique requirements.',
    'home.services.n8n': 'N8N Automation',
    'home.services.n8n.desc': 'Workflow automation and integration solutions to streamline operations.',
    'home.services.automation': 'Process Automation',
    'home.services.automation.desc': 'Automated workflows and business process optimization.',
    'home.services.learnMore': 'Learn More',

    'home.projects.title': 'Success Stories',
    'home.projects.subtitle': 'Real results from our client partnerships and innovative solutions.',
    'home.projects.viewCase': 'View Case Study',

    'home.testimonials.title': 'What Our Clients Say',

    'home.logistics.title': 'Specialized Solutions for Logistics & Retail',
    'home.logistics.subtitle': 'Industry-specific expertise that drives operational excellence and competitive advantage.',
    'home.logistics.supply.title': 'Supply Chain Optimization',
    'home.logistics.supply.desc': 'Advanced logistics management and inventory optimization solutions.',
    'home.logistics.supply.feature1': 'Real-time inventory tracking',
    'home.logistics.supply.feature2': 'Automated procurement processes',
    'home.logistics.supply.feature3': 'Demand forecasting and planning',
    'home.logistics.retail.title': 'Retail Management',
    'home.logistics.retail.desc': 'Complete retail operations management from POS to back-office.',
    'home.logistics.retail.feature1': 'Multi-channel sales integration',
    'home.logistics.retail.feature2': 'Customer relationship management',
    'home.logistics.retail.feature3': 'Analytics and reporting dashboards',
    'home.logistics.expertise.title': 'Industry Expertise',
    'home.logistics.expertise.desc': 'Deep understanding of logistics and retail challenges.',
    'home.logistics.expertise.stat1': 'Projects',
    'home.logistics.expertise.stat2': 'Success Rate',
    'home.logistics.cta': 'Explore Our Solutions',

    'home.cta.title': 'Ready to Transform Your Business?',
    'home.cta.subtitle': 'Let\'s discuss how our expertise can help you achieve your business goals with innovative technology solutions.',
    'home.cta.schedule': 'Schedule Consultation',
    'home.cta.contact': 'Contact Us Today',

    // Services Page
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive technology solutions designed to transform your business operations and drive sustainable growth.',
    'services.keyBenefits': 'Key Benefits',
    'services.whatWeOffer': 'What We Offer',

    'services.openbravo.title': 'Openbravo ERP Solutions',
    'services.openbravo.description': 'Transform your business operations with Openbravo\'s powerful, flexible ERP platform. We provide end-to-end implementation, customization, and support services.',
    'services.openbravo.benefits': 'Streamline operations, improve visibility, and enhance decision-making with real-time business insights.',
    'services.openbravo.point1': 'Complete ERP implementation and configuration',
    'services.openbravo.point2': 'Custom module development and integration',
    'services.openbravo.point3': 'Data migration and system optimization',
    'services.openbravo.point4': 'Training and ongoing technical support',
    'services.openbravo.cta': 'Get Openbravo Consultation',

    'services.odoo.title': 'Odoo Business Solutions',
    'services.odoo.description': 'Leverage Odoo\'s comprehensive suite of business applications to manage all aspects of your company from a single, integrated platform.',
    'services.odoo.benefits': 'Reduce complexity, increase efficiency, and scale your business with Odoo\'s modular approach.',
    'services.odoo.point1': 'Full Odoo implementation and customization',
    'services.odoo.point2': 'Module selection and configuration',
    'services.odoo.point3': 'Third-party integrations and API development',
    'services.odoo.point4': 'User training and change management',
    'services.odoo.point5': 'Ongoing maintenance and support',
    'services.odoo.cta': 'Start Your Odoo Project',

    'services.ai.title': 'AI & Machine Learning Solutions',
    'services.ai.description': 'Harness the power of artificial intelligence to automate processes, gain insights, and make data-driven decisions that propel your business forward.',
    'services.ai.benefits': 'Increase efficiency, reduce costs, and unlock new opportunities with intelligent automation and predictive analytics.',
    'services.ai.point1': 'Predictive analytics and forecasting',
    'services.ai.point2': 'Process automation and optimization',
    'services.ai.point3': 'Natural language processing solutions',
    'services.ai.point4': 'Computer vision and image recognition',
    'services.ai.point5': 'Machine learning model development',
    'services.ai.point6': 'AI strategy consulting and roadmapping',
    'services.ai.point7': 'Data preparation and model training',
    'services.ai.point8': 'AI solution deployment and monitoring',
    'services.ai.cta': 'Explore AI Solutions',

    'services.custom.title': 'Custom Software Development',
    'services.custom.description': 'Get software solutions built specifically for your unique business requirements. Our experienced team delivers scalable, maintainable applications.',
    'services.custom.benefits': 'Perfect fit for your processes, full ownership of the solution, and competitive advantage through custom functionality.',
    'services.custom.point1': 'Web and mobile application development',
    'services.custom.point2': 'API development and system integration',
    'services.custom.point3': 'Database design and optimization',
    'services.custom.point4': 'Cloud deployment and DevOps',
    'services.custom.point5': 'Quality assurance and testing',
    'services.custom.cta': 'Discuss Your Project',

    'services.consulting.title': 'Technical Consulting',
    'services.consulting.description': 'Strategic technology guidance to help you make informed decisions about your IT infrastructure, software architecture, and digital transformation initiatives.',
    'services.consulting.benefits': 'Avoid costly mistakes, optimize your technology investments, and accelerate your digital transformation journey.',
    'services.consulting.point1': 'Technology assessment and auditing',
    'services.consulting.point2': 'Architecture design and planning',
    'services.consulting.point3': 'Digital transformation strategy',
    'services.consulting.point4': 'Performance optimization consulting',
    'services.consulting.point5': 'Security and compliance guidance',
    'services.consulting.cta': 'Get Expert Advice',

    'services.finalCta.title': 'Ready to Get Started?',
    'services.finalCta.subtitle': 'Contact us today to discuss your project requirements and discover how we can help transform your business.',
    'services.finalCta.button': 'Start Your Project',

    // Solutions Page
    'solutions.title': 'Industry Solutions',
    'solutions.subtitle': 'Specialized solutions designed for specific industries, combining deep domain expertise with cutting-edge technology.',
    'solutions.keyFeatures': 'Key Features',
    'solutions.expectedBenefits': 'Expected Benefits',
    'solutions.learnMore': 'Learn More',

    'solutions.warehouse.title': 'Warehouse & Inventory Management',
    'solutions.warehouse.subtitle': 'Complete warehouse operations optimization',
    'solutions.warehouse.description': 'Streamline your warehouse operations with our comprehensive inventory management solution. From receiving to shipping, optimize every aspect of your warehouse workflow.',
    'solutions.warehouse.feature1': 'Real-time inventory tracking',
    'solutions.warehouse.feature2': 'Automated stock replenishment',
    'solutions.warehouse.feature3': 'Barcode and RFID integration',
    'solutions.warehouse.feature4': 'Pick, pack, and ship optimization',
    'solutions.warehouse.feature5': 'Multi-location inventory management',
    'solutions.warehouse.feature6': 'Demand forecasting and planning',
    'solutions.warehouse.feature7': 'Supplier management and procurement',
    'solutions.warehouse.feature8': 'Quality control and inspection workflows',
    'solutions.warehouse.feature9': 'Returns and reverse logistics',
    'solutions.warehouse.feature10': 'Advanced reporting and analytics',
    'solutions.warehouse.benefit1': 'Reduce inventory carrying costs by 20-30%',
    'solutions.warehouse.benefit2': 'Improve order accuracy to 99.5%+',
    'solutions.warehouse.benefit3': 'Increase warehouse productivity by 25%',
    'solutions.warehouse.benefit4': 'Minimize stockouts and overstock situations',
    'solutions.warehouse.benefit5': 'Enhance supplier relationships and negotiations',
    'solutions.warehouse.benefit6': 'Reduce manual errors and labor costs',
    'solutions.warehouse.benefit7': 'Improve customer satisfaction with faster deliveries',
    'solutions.warehouse.benefit8': 'Better visibility into inventory movements and trends',

    'solutions.delivery.title': 'Delivery & Logistics Optimization',
    'solutions.delivery.subtitle': 'End-to-end logistics and delivery management',
    'solutions.delivery.description': 'Optimize your delivery operations with intelligent route planning, real-time tracking, and automated logistics management. Reduce costs while improving customer satisfaction.',
    'solutions.delivery.feature1': 'Intelligent route optimization',
    'solutions.delivery.feature2': 'Real-time delivery tracking',
    'solutions.delivery.feature3': 'Driver mobile applications',
    'solutions.delivery.feature4': 'Customer notification system',
    'solutions.delivery.feature5': 'Fleet management and maintenance',
    'solutions.delivery.feature6': 'Proof of delivery capture',
    'solutions.delivery.feature7': 'Multi-carrier integration',
    'solutions.delivery.feature8': 'Delivery performance analytics',
    'solutions.delivery.feature9': 'Exception handling and alerts',
    'solutions.delivery.feature10': 'Cost analysis and optimization',
    'solutions.delivery.benefit1': 'Reduce delivery costs by 15-25%',
    'solutions.delivery.benefit2': 'Improve on-time delivery rates to 95%+',
    'solutions.delivery.benefit3': 'Increase customer satisfaction scores',
    'solutions.delivery.benefit4': 'Optimize fleet utilization and reduce fuel costs',
    'solutions.delivery.benefit5': 'Enhance visibility for customers and management',
    'solutions.delivery.benefit6': 'Reduce manual planning and coordination time',
    'solutions.delivery.benefit7': 'Improve driver productivity and satisfaction',
    'solutions.delivery.benefit8': 'Better handling of delivery exceptions and issues',

    'solutions.services.title': 'Service Management Solutions',
    'solutions.services.subtitle': 'Comprehensive service operations management',
    'solutions.services.description': 'Manage your service operations efficiently with our integrated solution covering scheduling, resource management, customer communication, and performance tracking.',
    'solutions.services.feature1': 'Service scheduling and dispatch',
    'solutions.services.feature2': 'Technician mobile applications',
    'solutions.services.feature3': 'Customer portal and communication',
    'solutions.services.feature4': 'Inventory and parts management',
    'solutions.services.feature5': 'Service contract management',
    'solutions.services.feature6': 'Performance tracking and KPIs',
    'solutions.services.benefit1': 'Improve first-time fix rates by 20%',
    'solutions.services.benefit2': 'Reduce service response times',
    'solutions.services.benefit3': 'Increase technician productivity',
    'solutions.services.benefit4': 'Enhance customer satisfaction and retention',

    'solutions.whyChoose.title': 'Why Choose Our Solutions?',
    'solutions.whyChoose.expertise.title': 'Industry Expertise',
    'solutions.whyChoose.expertise.desc': 'Deep understanding of industry-specific challenges and requirements.',
    'solutions.whyChoose.results.title': 'Proven Results',
    'solutions.whyChoose.results.desc': 'Track record of successful implementations and measurable improvements.',
    'solutions.whyChoose.scalable.title': 'Scalable Solutions',
    'solutions.whyChoose.scalable.desc': 'Solutions that grow with your business and adapt to changing needs.',
    'solutions.whyChoose.support.title': '24/7 Support',
    'solutions.whyChoose.support.desc': 'Comprehensive support and maintenance to ensure optimal performance.',

    'solutions.cta.title': 'Transform Your Operations Today',
    'solutions.cta.subtitle': 'Ready to optimize your business processes? Let\'s discuss how our solutions can drive efficiency and growth.',
    'solutions.cta.button': 'Get Started',

    // Projects Page
    'projects.title': 'Our Success Stories',
    'projects.subtitle': 'Discover how we\'ve helped businesses transform their operations and achieve remarkable results through innovative technology solutions.',
    'projects.filters.all': 'All Projects',
    'projects.filters.openbravo': 'Openbravo',
    'projects.filters.odoo': 'Odoo',
    'projects.filters.ai': 'AI Solutions',
    'projects.filters.custom': 'Custom Development',
    'projects.keyResults': 'Key Results',
    'projects.viewCase': 'View Case Study',

    'projects.halsted.title': 'Halsted Logistics Optimization',
    'projects.halsted.desc': 'Complete Openbravo ERP implementation for logistics company, optimizing inventory management and reducing operational costs by 30%.',
    'projects.halsted.sector': 'Logistics',
    'projects.halsted.result1': '30% reduction in inventory costs',
    'projects.halsted.result2': '25% faster order processing',
    'projects.halsted.result3': '99.5% inventory accuracy',
    'projects.halsted.testimonial': 'Thanks to Doce Leguas, our operations have drastically improved. Their professionalism and knowledge are exceptional.',
    'projects.halsted.client': 'Brian, Operations Manager at Halsted',

    'projects.ai.title': 'AI Predictive Analytics Platform',
    'projects.ai.desc': 'Custom AI solution for demand forecasting and inventory optimization, resulting in 40% improvement in decision-making accuracy.',
    'projects.ai.sector': 'Manufacturing',
    'projects.ai.result1': '40% improvement in forecast accuracy',
    'projects.ai.result2': '20% reduction in stockouts',
    'projects.ai.result3': '15% decrease in inventory costs',
    'projects.ai.testimonial': 'The AI solution exceeded all our expectations. The predictive capabilities have transformed our planning process.',
    'projects.ai.client': 'Maria Rodriguez, Supply Chain Director',

    'projects.custom.title': 'Custom ERP Solution',
    'projects.custom.desc': 'Bespoke enterprise resource planning system designed specifically for manufacturing processes, increasing operational efficiency by 45%.',
    'projects.custom.sector': 'Manufacturing',
    'projects.custom.result1': '45% increase in operational efficiency',
    'projects.custom.result2': '60% reduction in manual processes',
    'projects.custom.result3': '35% faster reporting and analytics',
    'projects.custom.testimonial': 'The custom solution perfectly fits our unique requirements. It\'s exactly what we needed.',
    'projects.custom.client': 'John Smith, CEO at ManufactureCorp',

    'projects.odoo.title': 'Odoo Complete Implementation',
    'projects.odoo.desc': 'Full Odoo suite implementation for retail chain, integrating sales, inventory, accounting, and HR modules for unified operations.',
    'projects.odoo.sector': 'Retail',
    'projects.odoo.result1': '50% reduction in administrative tasks',
    'projects.odoo.result2': '30% improvement in inventory turnover',
    'projects.odoo.result3': '25% increase in sales productivity',
    'projects.odoo.testimonial': 'Odoo has unified our operations completely. Everything is now connected and efficient.',
    'projects.odoo.client': 'Sarah Johnson, Operations Director',

    'projects.warehouse.title': 'Smart Warehouse Management',
    'projects.warehouse.desc': 'AI-powered warehouse management system with automated inventory tracking and predictive maintenance capabilities.',
    'projects.warehouse.sector': 'Logistics',
    'projects.warehouse.result1': '35% improvement in picking efficiency',
    'projects.warehouse.result2': '90% reduction in inventory discrepancies',
    'projects.warehouse.result3': '25% decrease in operational costs',
    'projects.warehouse.testimonial': 'The smart warehouse solution has revolutionized our operations. Everything is automated and efficient.',
    'projects.warehouse.client': 'Mike Davis, Warehouse Manager',

    'projects.cloud.title': 'Cloud Migration & Optimization',
    'projects.cloud.desc': 'Complete cloud infrastructure migration with performance optimization and cost reduction strategies.',
    'projects.cloud.sector': 'Technology',
    'projects.cloud.result1': '40% reduction in infrastructure costs',
    'projects.cloud.result2': '99.9% system uptime achieved',
    'projects.cloud.result3': '50% improvement in system performance',
    'projects.cloud.testimonial': 'The cloud migration was seamless and the performance improvements are remarkable.',
    'projects.cloud.client': 'Robert Kim, IT Director at SteelWorks Inc',

    'projects.featured.title': 'Featured Case Study: Halsted Logistics',
    'projects.featured.challenge': 'The Challenge',
    'projects.featured.challengeDesc': 'Halsted faced significant challenges with inventory management, manual processes, and lack of real-time visibility across their logistics operations.',
    'projects.featured.solution': 'Our Solution',
    'projects.featured.solutionDesc': 'We implemented a comprehensive Openbravo ERP solution with custom modules for logistics optimization, automated workflows, and real-time reporting.',
    'projects.featured.results': 'The Results',
    'projects.featured.costReduction': 'Cost Reduction',
    'projects.featured.fasterDelivery': 'Faster Delivery',

    'projects.cta.title': 'Ready to Start Your Success Story?',
    'projects.cta.subtitle': 'Let\'s discuss how we can help transform your business with innovative technology solutions.',
    'projects.cta.button': 'Start Your Project',

    // About Page
    'about.title': 'About Doce Leguas',
    'about.subtitle': 'We are a team of passionate technology experts dedicated to transforming businesses through innovative software solutions and strategic consulting.',

    'about.story.title': 'Our Story',
    'about.story.content1': 'Founded with a vision to bridge the gap between complex technology and business success, Doce Leguas has grown into a trusted partner for companies seeking digital transformation.',
    'about.story.content2': 'Our journey began with a simple belief: that the right technology, properly implemented, can unlock tremendous value for businesses of all sizes. Today, we continue to help organizations achieve their goals through innovative solutions.',

    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be the leading provider of innovative business technology solutions, empowering organizations to achieve operational excellence and sustainable growth.',

    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles that guide everything we do and define who we are as a company.',
    'about.values.excellence': 'Excellence',
    'about.values.innovation': 'Innovation',
    'about.values.integrity': 'Integrity',
    'about.values.customer': 'Customer Focus',
    'about.values.collaboration': 'Collaboration',

    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'Experienced professionals passionate about technology and committed to your success.',
    'about.team.nono.position': 'Founder & CEO',
    'about.team.nono.description': 'Visionary leader with extensive experience in enterprise software solutions and business transformation.',
    'about.team.mark.position': 'CTO & Lead Developer',
    'about.team.mark.description': 'Technical expert specializing in ERP systems, AI solutions, and custom software development.',
    'about.team.rafael.position': 'Senior Solutions Architect',
    'about.team.rafael.description': 'Experienced architect focused on designing scalable, efficient solutions for complex business requirements.',
    'about.team.maarten.position': 'Business Development Director',
    'about.team.maarten.description': 'Strategic business leader focused on building partnerships and driving growth through innovative solutions.',

    'about.culture.title': 'Our Culture',
    'about.culture.content1': 'We foster a collaborative environment where innovation thrives and every team member is empowered to contribute their best work.',
    'about.culture.content2': 'Our culture is built on mutual respect, continuous learning, and a shared commitment to delivering exceptional results for our clients.',
    'about.culture.item1': 'Continuous Learning',
    'about.culture.item2': 'Innovation Focus',
    'about.culture.item3': 'Team Collaboration',
    'about.culture.item4': 'Client Success',

    'about.cta.title': 'Ready to Work Together?',
    'about.cta.subtitle': 'Let\'s discuss how our expertise and passion can help drive your business forward.',
    'about.cta.contact': 'Get in Touch',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Ready to transform your business? Get in touch with our team of experts to discuss your project requirements and discover how we can help.',

    'contact.form.title': 'Send us a Message',
    'contact.form.fullName': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.company': 'Company',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.success': 'Message Sent Successfully!',
    'contact.form.successDesc': 'Thank you for contacting us. We\'ll get back to you within 24 hours.',
    'contact.form.selectSubject': 'Select a subject...',

    'contact.form.placeholders.fullName': 'Enter your full name',
    'contact.form.placeholders.email': 'Enter your email address',
    'contact.form.placeholders.phone': 'Enter your phone number',
    'contact.form.placeholders.company': 'Enter your company name',
    'contact.form.placeholders.message': 'Tell us about your project or requirements...',

    'contact.form.subjects.generalinquiry': 'General Inquiry',
    'contact.form.subjects.openbravoconsultation': 'Openbravo Consultation',
    'contact.form.subjects.odooimplementation': 'Odoo Implementation',
    'contact.form.subjects.aisolutions': 'AI Solutions',
    'contact.form.subjects.customdevelopment': 'Custom Development',
    'contact.form.subjects.technicalsupport': 'Technical Support',
    'contact.form.subjects.partnershipopportunity': 'Partnership Opportunity',
    'contact.form.subjects.other': 'Other',

    'contact.info.title': 'Get in Touch',
    'contact.info.email': 'Email',
    'contact.info.emailDesc': 'Send us an email anytime',
    'contact.info.phone': 'Phone',
    'contact.info.phoneDesc': 'Call us during business hours',
    'contact.info.office': 'Office Locations',
    'contact.info.officeDesc': 'Visit us at our offices',
    'contact.info.hours': 'Business Hours',
    'contact.info.hoursDesc': '9:00 AM - 6:00 PM (GMT)',

    'contact.whyContact.title': 'Why Contact Us?',
    'contact.whyContact.item1': 'Free initial consultation and project assessment',
    'contact.whyContact.item2': 'Customized solutions tailored to your specific needs',
    'contact.whyContact.item3': 'Expert team with proven track record in enterprise solutions',
    'contact.whyContact.item4': 'Ongoing support and maintenance for all our implementations',

    // Footer
    'footer.description': 'Transforming businesses through innovative technology solutions and expert consulting services.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contactInfo': 'Contact Info',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'footer.sitemap': 'Sitemap',

    // ChatBot
    'chatbot.title': 'Doce Leguas Assistant',
    'chatbot.subtitle': 'How can we help you today?',
    'chatbot.welcome': 'Hello! I\'m here to help you learn more about our services and solutions. How can I assist you today?',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.open': 'Open chat',
    'chatbot.close': 'Close chat',
    'chatbot.defaultResponse': 'Thank you for your message. Our team will get back to you soon with more information.',
    'chatbot.errorMessage': 'I\'m sorry, I\'m having trouble connecting right now. Please try again later or contact us directly.'
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.solutions': 'Soluciones',
    'nav.projects': 'Proyectos',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.getStarted': 'Comenzar',

    // Home Page
    'home.hero.title': 'Transforma Tu Negocio con Soluciones Tecnológicas Innovadoras',
    'home.hero.subtitle': 'Nos especializamos en Openbravo ERP, Odoo, soluciones de IA y desarrollo personalizado para optimizar tus procesos empresariales e impulsar el crecimiento.',
    'home.hero.viewServices': 'Ver Nuestros Servicios',
    'home.hero.startProject': 'Iniciar Tu Proyecto',

    'home.valueProps.title': '¿Por Qué Elegir Doce Leguas?',
    'home.valueProps.subtitle': 'Combinamos experiencia técnica con comprensión empresarial para entregar soluciones que realmente transforman tus operaciones.',
    'home.valueProps.innovation': 'Innovación',
    'home.valueProps.innovation.desc': 'Nos mantenemos a la vanguardia de la tecnología para proporcionar soluciones de última generación.',
    'home.valueProps.custom': 'Personalización',
    'home.valueProps.custom.desc': 'Cada solución está adaptada a tus necesidades y objetivos empresariales específicos.',
    'home.valueProps.results': 'Resultados',
    'home.valueProps.results.desc': 'Nos enfocamos en resultados medibles que generen valor empresarial real.',
    'home.valueProps.team': 'Equipo Experto',
    'home.valueProps.team.desc': 'Nuestros profesionales experimentados aportan profunda experiencia en soluciones empresariales.',

    'home.services.title': 'Nuestros Servicios Principales',
    'home.services.subtitle': 'Soluciones tecnológicas integrales diseñadas para acelerar el crecimiento de tu negocio.',
    'home.services.openbravo': 'Openbravo ERP',
    'home.services.openbravo.desc': 'Implementación y personalización completa de ERP para planificación de recursos empresariales.',
    'home.services.odoo': 'Soluciones Odoo',
    'home.services.odoo.desc': 'Gestión empresarial integral con la suite integrada de aplicaciones de Odoo.',
    'home.services.ai': 'Soluciones de IA',
    'home.services.ai.desc': 'Automatización inteligente y análisis de datos para optimizar tus procesos empresariales.',
    'home.services.custom': 'Desarrollo Personalizado',
    'home.services.custom.desc': 'Soluciones de software a medida construidas específicamente para tus requisitos únicos.',
    'home.services.n8n': 'Automatización N8N',
    'home.services.n8n.desc': 'Soluciones de automatización de flujos de trabajo e integración para optimizar operaciones.',
    'home.services.automation': 'Automatización de Procesos',
    'home.services.automation.desc': 'Flujos de trabajo automatizados y optimización de procesos empresariales.',
    'home.services.learnMore': 'Saber Más',

    'home.projects.title': 'Historias de Éxito',
    'home.projects.subtitle': 'Resultados reales de nuestras alianzas con clientes y soluciones innovadoras.',
    'home.projects.viewCase': 'Ver Caso de Estudio',

    'home.testimonials.title': 'Lo Que Dicen Nuestros Clientes',

    'home.logistics.title': 'Soluciones Especializadas para Logística y Retail',
    'home.logistics.subtitle': 'Experiencia específica de la industria que impulsa la excelencia operacional y la ventaja competitiva.',
    'home.logistics.supply.title': 'Optimización de Cadena de Suministro',
    'home.logistics.supply.desc': 'Soluciones avanzadas de gestión logística y optimización de inventario.',
    'home.logistics.supply.feature1': 'Seguimiento de inventario en tiempo real',
    'home.logistics.supply.feature2': 'Procesos de adquisición automatizados',
    'home.logistics.supply.feature3': 'Pronóstico y planificación de demanda',
    'home.logistics.retail.title': 'Gestión de Retail',
    'home.logistics.retail.desc': 'Gestión completa de operaciones de retail desde POS hasta back-office.',
    'home.logistics.retail.feature1': 'Integración de ventas multicanal',
    'home.logistics.retail.feature2': 'Gestión de relaciones con clientes',
    'home.logistics.retail.feature3': 'Paneles de análisis y reportes',
    'home.logistics.expertise.title': 'Experiencia en la Industria',
    'home.logistics.expertise.desc': 'Comprensión profunda de los desafíos de logística y retail.',
    'home.logistics.expertise.stat1': 'Proyectos',
    'home.logistics.expertise.stat2': 'Tasa de Éxito',
    'home.logistics.cta': 'Explorar Nuestras Soluciones',

    'home.cta.title': '¿Listo para Transformar Tu Negocio?',
    'home.cta.subtitle': 'Hablemos sobre cómo nuestra experiencia puede ayudarte a alcanzar tus objetivos empresariales con soluciones tecnológicas innovadoras.',
    'home.cta.schedule': 'Programar Consulta',
    'home.cta.contact': 'Contáctanos Hoy',

    // Services Page
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones tecnológicas integrales diseñadas para transformar las operaciones de tu negocio e impulsar un crecimiento sostenible.',
    'services.keyBenefits': 'Beneficios Clave',
    'services.whatWeOffer': 'Lo Que Ofrecemos',

    'services.openbravo.title': 'Soluciones Openbravo ERP',
    'services.openbravo.description': 'Transforma las operaciones de tu negocio con la plataforma ERP potente y flexible de Openbravo. Proporcionamos servicios completos de implementación, personalización y soporte.',
    'services.openbravo.benefits': 'Optimiza operaciones, mejora la visibilidad y potencia la toma de decisiones con información empresarial en tiempo real.',
    'services.openbravo.point1': 'Implementación y configuración completa de ERP',
    'services.openbravo.point2': 'Desarrollo e integración de módulos personalizados',
    'services.openbravo.point3': 'Migración de datos y optimización del sistema',
    'services.openbravo.point4': 'Capacitación y soporte técnico continuo',
    'services.openbravo.cta': 'Obtener Consulta Openbravo',

    'services.odoo.title': 'Soluciones Empresariales Odoo',
    'services.odoo.description': 'Aprovecha la suite integral de aplicaciones empresariales de Odoo para gestionar todos los aspectos de tu empresa desde una sola plataforma integrada.',
    'services.odoo.benefits': 'Reduce la complejidad, aumenta la eficiencia y escala tu negocio con el enfoque modular de Odoo.',
    'services.odoo.point1': 'Implementación y personalización completa de Odoo',
    'services.odoo.point2': 'Selección y configuración de módulos',
    'services.odoo.point3': 'Integraciones de terceros y desarrollo de API',
    'services.odoo.point4': 'Capacitación de usuarios y gestión del cambio',
    'services.odoo.point5': 'Mantenimiento y soporte continuo',
    'services.odoo.cta': 'Iniciar Tu Proyecto Odoo',

    'services.ai.title': 'Soluciones de IA y Machine Learning',
    'services.ai.description': 'Aprovecha el poder de la inteligencia artificial para automatizar procesos, obtener insights y tomar decisiones basadas en datos que impulsen tu negocio hacia adelante.',
    'services.ai.benefits': 'Aumenta la eficiencia, reduce costos y desbloquea nuevas oportunidades con automatización inteligente y análisis predictivo.',
    'services.ai.point1': 'Análisis predictivo y pronósticos',
    'services.ai.point2': 'Automatización y optimización de procesos',
    'services.ai.point3': 'Soluciones de procesamiento de lenguaje natural',
    'services.ai.point4': 'Visión por computadora y reconocimiento de imágenes',
    'services.ai.point5': 'Desarrollo de modelos de machine learning',
    'services.ai.point6': 'Consultoría y hoja de ruta de estrategia de IA',
    'services.ai.point7': 'Preparación de datos y entrenamiento de modelos',
    'services.ai.point8': 'Despliegue y monitoreo de soluciones de IA',
    'services.ai.cta': 'Explorar Soluciones de IA',

    'services.custom.title': 'Desarrollo de Software Personalizado',
    'services.custom.description': 'Obtén soluciones de software construidas específicamente para tus requisitos empresariales únicos. Nuestro equipo experimentado entrega aplicaciones escalables y mantenibles.',
    'services.custom.benefits': 'Ajuste perfecto para tus procesos, propiedad completa de la solución y ventaja competitiva a través de funcionalidad personalizada.',
    'services.custom.point1': 'Desarrollo de aplicaciones web y móviles',
    'services.custom.point2': 'Desarrollo de API e integración de sistemas',
    'services.custom.point3': 'Diseño y optimización de bases de datos',
    'services.custom.point4': 'Despliegue en la nube y DevOps',
    'services.custom.point5': 'Aseguramiento de calidad y pruebas',
    'services.custom.cta': 'Discutir Tu Proyecto',

    'services.consulting.title': 'Consultoría Técnica',
    'services.consulting.description': 'Orientación tecnológica estratégica para ayudarte a tomar decisiones informadas sobre tu infraestructura de TI, arquitectura de software e iniciativas de transformación digital.',
    'services.consulting.benefits': 'Evita errores costosos, optimiza tus inversiones tecnológicas y acelera tu viaje de transformación digital.',
    'services.consulting.point1': 'Evaluación y auditoría tecnológica',
    'services.consulting.point2': 'Diseño y planificación de arquitectura',
    'services.consulting.point3': 'Estrategia de transformación digital',
    'services.consulting.point4': 'Consultoría de optimización de rendimiento',
    'services.consulting.point5': 'Orientación en seguridad y cumplimiento',
    'services.consulting.cta': 'Obtener Asesoramiento Experto',

    'services.finalCta.title': '¿Listo para Comenzar?',
    'services.finalCta.subtitle': 'Contáctanos hoy para discutir los requisitos de tu proyecto y descubrir cómo podemos ayudar a transformar tu negocio.',
    'services.finalCta.button': 'Iniciar Tu Proyecto',

    // Solutions Page
    'solutions.title': 'Soluciones por Industria',
    'solutions.subtitle': 'Soluciones especializadas diseñadas para industrias específicas, combinando experiencia profunda del dominio con tecnología de vanguardia.',
    'solutions.keyFeatures': 'Características Clave',
    'solutions.expectedBenefits': 'Beneficios Esperados',
    'solutions.learnMore': 'Saber Más',

    'solutions.warehouse.title': 'Gestión de Almacén e Inventario',
    'solutions.warehouse.subtitle': 'Optimización completa de operaciones de almacén',
    'solutions.warehouse.description': 'Optimiza las operaciones de tu almacén con nuestra solución integral de gestión de inventario. Desde recepción hasta envío, optimiza cada aspecto del flujo de trabajo de tu almacén.',
    'solutions.warehouse.feature1': 'Seguimiento de inventario en tiempo real',
    'solutions.warehouse.feature2': 'Reposición automática de stock',
    'solutions.warehouse.feature3': 'Integración de códigos de barras y RFID',
    'solutions.warehouse.feature4': 'Optimización de picking, packing y envío',
    'solutions.warehouse.feature5': 'Gestión de inventario multi-ubicación',
    'solutions.warehouse.feature6': 'Pronóstico y planificación de demanda',
    'solutions.warehouse.feature7': 'Gestión de proveedores y adquisiciones',
    'solutions.warehouse.feature8': 'Flujos de trabajo de control de calidad e inspección',
    'solutions.warehouse.feature9': 'Devoluciones y logística inversa',
    'solutions.warehouse.feature10': 'Reportes avanzados y análisis',
    'solutions.warehouse.benefit1': 'Reducir costos de mantenimiento de inventario en 20-30%',
    'solutions.warehouse.benefit2': 'Mejorar precisión de pedidos a 99.5%+',
    'solutions.warehouse.benefit3': 'Aumentar productividad del almacén en 25%',
    'solutions.warehouse.benefit4': 'Minimizar situaciones de desabastecimiento y exceso de stock',
    'solutions.warehouse.benefit5': 'Mejorar relaciones con proveedores y negociaciones',
    'solutions.warehouse.benefit6': 'Reducir errores manuales y costos laborales',
    'solutions.warehouse.benefit7': 'Mejorar satisfacción del cliente con entregas más rápidas',
    'solutions.warehouse.benefit8': 'Mejor visibilidad de movimientos y tendencias de inventario',

    'solutions.delivery.title': 'Optimización de Entrega y Logística',
    'solutions.delivery.subtitle': 'Gestión integral de logística y entrega de extremo a extremo',
    'solutions.delivery.description': 'Optimiza tus operaciones de entrega con planificación inteligente de rutas, seguimiento en tiempo real y gestión automatizada de logística. Reduce costos mientras mejoras la satisfacción del cliente.',
    'solutions.delivery.feature1': 'Optimización inteligente de rutas',
    'solutions.delivery.feature2': 'Seguimiento de entrega en tiempo real',
    'solutions.delivery.feature3': 'Aplicaciones móviles para conductores',
    'solutions.delivery.feature4': 'Sistema de notificaciones al cliente',
    'solutions.delivery.feature5': 'Gestión y mantenimiento de flota',
    'solutions.delivery.feature6': 'Captura de prueba de entrega',
    'solutions.delivery.feature7': 'Integración multi-transportista',
    'solutions.delivery.feature8': 'Análisis de rendimiento de entrega',
    'solutions.delivery.feature9': 'Manejo de excepciones y alertas',
    'solutions.delivery.feature10': 'Análisis y optimización de costos',
    'solutions.delivery.benefit1': 'Reducir costos de entrega en 15-25%',
    'solutions.delivery.benefit2': 'Mejorar tasas de entrega a tiempo a 95%+',
    'solutions.delivery.benefit3': 'Aumentar puntuaciones de satisfacción del cliente',
    'solutions.delivery.benefit4': 'Optimizar utilización de flota y reducir costos de combustible',
    'solutions.delivery.benefit5': 'Mejorar visibilidad para clientes y gestión',
    'solutions.delivery.benefit6': 'Reducir tiempo de planificación y coordinación manual',
    'solutions.delivery.benefit7': 'Mejorar productividad y satisfacción del conductor',
    'solutions.delivery.benefit8': 'Mejor manejo de excepciones y problemas de entrega',

    'solutions.services.title': 'Soluciones de Gestión de Servicios',
    'solutions.services.subtitle': 'Gestión integral de operaciones de servicio',
    'solutions.services.description': 'Gestiona tus operaciones de servicio de manera eficiente con nuestra solución integrada que cubre programación, gestión de recursos, comunicación con clientes y seguimiento de rendimiento.',
    'solutions.services.feature1': 'Programación y despacho de servicios',
    'solutions.services.feature2': 'Aplicaciones móviles para técnicos',
    'solutions.services.feature3': 'Portal del cliente y comunicación',
    'solutions.services.feature4': 'Gestión de inventario y repuestos',
    'solutions.services.feature5': 'Gestión de contratos de servicio',
    'solutions.services.feature6': 'Seguimiento de rendimiento y KPIs',
    'solutions.services.benefit1': 'Mejorar tasas de reparación en primera visita en 20%',
    'solutions.services.benefit2': 'Reducir tiempos de respuesta de servicio',
    'solutions.services.benefit3': 'Aumentar productividad de técnicos',
    'solutions.services.benefit4': 'Mejorar satisfacción y retención de clientes',

    'solutions.whyChoose.title': '¿Por Qué Elegir Nuestras Soluciones?',
    'solutions.whyChoose.expertise.title': 'Experiencia en la Industria',
    'solutions.whyChoose.expertise.desc': 'Comprensión profunda de desafíos y requisitos específicos de la industria.',
    'solutions.whyChoose.results.title': 'Resultados Comprobados',
    'solutions.whyChoose.results.desc': 'Historial de implementaciones exitosas y mejoras medibles.',
    'solutions.whyChoose.scalable.title': 'Soluciones Escalables',
    'solutions.whyChoose.scalable.desc': 'Soluciones que crecen con tu negocio y se adaptan a necesidades cambiantes.',
    'solutions.whyChoose.support.title': 'Soporte 24/7',
    'solutions.whyChoose.support.desc': 'Soporte integral y mantenimiento para asegurar rendimiento óptimo.',

    'solutions.cta.title': 'Transforma Tus Operaciones Hoy',
    'solutions.cta.subtitle': '¿Listo para optimizar tus procesos empresariales? Hablemos sobre cómo nuestras soluciones pueden impulsar eficiencia y crecimiento.',
    'solutions.cta.button': 'Comenzar',

    // Projects Page
    'projects.title': 'Nuestras Historias de Éxito',
    'projects.subtitle': 'Descubre cómo hemos ayudado a empresas a transformar sus operaciones y lograr resultados extraordinarios a través de soluciones tecnológicas innovadoras.',
    'projects.filters.all': 'Todos los Proyectos',
    'projects.filters.openbravo': 'Openbravo',
    'projects.filters.odoo': 'Odoo',
    'projects.filters.ai': 'Soluciones de IA',
    'projects.filters.custom': 'Desarrollo Personalizado',
    'projects.keyResults': 'Resultados Clave',
    'projects.viewCase': 'Ver Caso de Estudio',

    'projects.halsted.title': 'Optimización Logística Halsted',
    'projects.halsted.desc': 'Implementación completa de Openbravo ERP para empresa logística, optimizando gestión de inventario y reduciendo costos operacionales en 30%.',
    'projects.halsted.sector': 'Logística',
    'projects.halsted.result1': '30% reducción en costos de inventario',
    'projects.halsted.result2': '25% procesamiento de pedidos más rápido',
    'projects.halsted.result3': '99.5% precisión de inventario',
    'projects.halsted.testimonial': 'Gracias a Doce Leguas, nuestras operaciones han mejorado drásticamente. Su profesionalismo y conocimiento son excepcionales.',
    'projects.halsted.client': 'Brian, Gerente de Operaciones en Halsted',

    'projects.ai.title': 'Plataforma de Análisis Predictivo con IA',
    'projects.ai.desc': 'Solución de IA personalizada para pronóstico de demanda y optimización de inventario, resultando en 40% de mejora en precisión de toma de decisiones.',
    'projects.ai.sector': 'Manufactura',
    'projects.ai.result1': '40% mejora en precisión de pronósticos',
    'projects.ai.result2': '20% reducción en desabastecimientos',
    'projects.ai.result3': '15% disminución en costos de inventario',
    'projects.ai.testimonial': 'La solución de IA superó todas nuestras expectativas. Las capacidades predictivas han transformado nuestro proceso de planificación.',
    'projects.ai.client': 'María Rodríguez, Directora de Cadena de Suministro',

    'projects.custom.title': 'Solución ERP Personalizada',
    'projects.custom.desc': 'Sistema de planificación de recursos empresariales a medida diseñado específicamente para procesos de manufactura, aumentando eficiencia operacional en 45%.',
    'projects.custom.sector': 'Manufactura',
    'projects.custom.result1': '45% aumento en eficiencia operacional',
    'projects.custom.result2': '60% reducción en procesos manuales',
    'projects.custom.result3': '35% reportes y análisis más rápidos',
    'projects.custom.testimonial': 'La solución personalizada se ajusta perfectamente a nuestros requisitos únicos. Es exactamente lo que necesitábamos.',
    'projects.custom.client': 'Juan Smith, CEO en ManufactureCorp',

    'projects.odoo.title': 'Implementación Completa de Odoo',
    'projects.odoo.desc': 'Implementación completa de la suite Odoo para cadena de retail, integrando módulos de ventas, inventario, contabilidad y RRHH para operaciones unificadas.',
    'projects.odoo.sector': 'Retail',
    'projects.odoo.result1': '50% reducción en tareas administrativas',
    'projects.odoo.result2': '30% mejora en rotación de inventario',
    'projects.odoo.result3': '25% aumento en productividad de ventas',
    'projects.odoo.testimonial': 'Odoo ha unificado completamente nuestras operaciones. Todo está ahora conectado y es eficiente.',
    'projects.odoo.client': 'Sarah Johnson, Directora de Operaciones',

    'projects.warehouse.title': 'Gestión Inteligente de Almacén',
    'projects.warehouse.desc': 'Sistema de gestión de almacén potenciado por IA con seguimiento automatizado de inventario y capacidades de mantenimiento predictivo.',
    'projects.warehouse.sector': 'Logística',
    'projects.warehouse.result1': '35% mejora en eficiencia de picking',
    'projects.warehouse.result2': '90% reducción en discrepancias de inventario',
    'projects.warehouse.result3': '25% disminución en costos operacionales',
    'projects.warehouse.testimonial': 'La solución de almacén inteligente ha revolucionado nuestras operaciones. Todo está automatizado y es eficiente.',
    'projects.warehouse.client': 'Mike Davis, Gerente de Almacén',

    'projects.cloud.title': 'Migración y Optimización en la Nube',
    'projects.cloud.desc': 'Migración completa de infraestructura en la nube con optimización de rendimiento y estrategias de reducción de costos.',
    'projects.cloud.sector': 'Tecnología',
    'projects.cloud.result1': '40% reducción en costos de infraestructura',
    'projects.cloud.result2': '99.9% tiempo de actividad del sistema logrado',
    'projects.cloud.result3': '50% mejora en rendimiento del sistema',
    'projects.cloud.testimonial': 'La migración a la nube fue perfecta y las mejoras de rendimiento son notables.',
    'projects.cloud.client': 'Robert Kim, Director de TI en SteelWorks Inc',

    'projects.featured.title': 'Caso de Estudio Destacado: Halsted Logistics',
    'projects.featured.challenge': 'El Desafío',
    'projects.featured.challengeDesc': 'Halsted enfrentaba desafíos significativos con gestión de inventario, procesos manuales y falta de visibilidad en tiempo real en sus operaciones logísticas.',
    'projects.featured.solution': 'Nuestra Solución',
    'projects.featured.solutionDesc': 'Implementamos una solución integral de Openbravo ERP con módulos personalizados para optimización logística, flujos de trabajo automatizados y reportes en tiempo real.',
    'projects.featured.results': 'Los Resultados',
    'projects.featured.costReduction': 'Reducción de Costos',
    'projects.featured.fasterDelivery': 'Entrega Más Rápida',

    'projects.cta.title': '¿Listo para Comenzar Tu Historia de Éxito?',
    'projects.cta.subtitle': 'Hablemos sobre cómo podemos ayudar a transformar tu negocio con soluciones tecnológicas innovadoras.',
    'projects.cta.button': 'Iniciar Tu Proyecto',

    // About Page
    'about.title': 'Acerca de Doce Leguas',
    'about.subtitle': 'Somos un equipo de expertos en tecnología apasionados, dedicados a transformar empresas a través de soluciones de software innovadoras y consultoría estratégica.',

    'about.story.title': 'Nuestra Historia',
    'about.story.content1': 'Fundada con la visión de cerrar la brecha entre la tecnología compleja y el éxito empresarial, Doce Leguas ha crecido hasta convertirse en un socio de confianza para empresas que buscan transformación digital.',
    'about.story.content2': 'Nuestro viaje comenzó con una creencia simple: que la tecnología correcta, implementada adecuadamente, puede desbloquear un valor tremendo para empresas de todos los tamaños. Hoy, continuamos ayudando a organizaciones a alcanzar sus objetivos a través de soluciones innovadoras.',

    'about.vision.title': 'Nuestra Visión',
    'about.vision.desc': 'Ser el proveedor líder de soluciones tecnológicas empresariales innovadoras, empoderando a las organizaciones para lograr excelencia operacional y crecimiento sostenible.',

    'about.values.title': 'Nuestros Valores',
    'about.values.subtitle': 'Los principios que guían todo lo que hacemos y definen quiénes somos como empresa.',
    'about.values.excellence': 'Excelencia',
    'about.values.innovation': 'Innovación',
    'about.values.integrity': 'Integridad',
    'about.values.customer': 'Enfoque en el Cliente',
    'about.values.collaboration': 'Colaboración',

    'about.team.title': 'Conoce Nuestro Equipo',
    'about.team.subtitle': 'Profesionales experimentados apasionados por la tecnología y comprometidos con tu éxito.',
    'about.team.nono.position': 'Fundador y CEO',
    'about.team.nono.description': 'Líder visionario con amplia experiencia en soluciones de software empresarial y transformación empresarial.',
    'about.team.mark.position': 'CTO y Desarrollador Principal',
    'about.team.mark.description': 'Experto técnico especializado en sistemas ERP, soluciones de IA y desarrollo de software personalizado.',
    'about.team.rafael.position': 'Arquitecto Senior de Soluciones',
    'about.team.rafael.description': 'Arquitecto experimentado enfocado en diseñar soluciones escalables y eficientes para requisitos empresariales complejos.',
    'about.team.maarten.position': 'Director de Desarrollo de Negocios',
    'about.team.maarten.description': 'Líder empresarial estratégico enfocado en construir alianzas e impulsar crecimiento a través de soluciones innovadoras.',

    'about.culture.title': 'Nuestra Cultura',
    'about.culture.content1': 'Fomentamos un ambiente colaborativo donde la innovación prospera y cada miembro del equipo está empoderado para contribuir con su mejor trabajo.',
    'about.culture.content2': 'Nuestra cultura está construida sobre respeto mutuo, aprendizaje continuo y un compromiso compartido de entregar resultados excepcionales para nuestros clientes.',
    'about.culture.item1': 'Aprendizaje Continuo',
    'about.culture.item2': 'Enfoque en Innovación',
    'about.culture.item3': 'Colaboración en Equipo',
    'about.culture.item4': 'Éxito del Cliente',

    'about.cta.title': '¿Listo para Trabajar Juntos?',
    'about.cta.subtitle': 'Hablemos sobre cómo nuestra experiencia y pasión pueden ayudar a impulsar tu negocio hacia adelante.',
    'about.cta.contact': 'Ponerse en Contacto',

    // Contact Page
    'contact.title': 'Contáctanos',
    'contact.subtitle': '¿Listo para transformar tu negocio? Ponte en contacto con nuestro equipo de expertos para discutir los requisitos de tu proyecto y descubrir cómo podemos ayudar.',

    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.fullName': 'Nombre Completo',
    'contact.form.email': 'Dirección de Email',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.company': 'Empresa',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.form.success': '¡Mensaje Enviado Exitosamente!',
    'contact.form.successDesc': 'Gracias por contactarnos. Te responderemos dentro de 24 horas.',
    'contact.form.selectSubject': 'Selecciona un asunto...',

    'contact.form.placeholders.fullName': 'Ingresa tu nombre completo',
    'contact.form.placeholders.email': 'Ingresa tu dirección de email',
    'contact.form.placeholders.phone': 'Ingresa tu número de teléfono',
    'contact.form.placeholders.company': 'Ingresa el nombre de tu empresa',
    'contact.form.placeholders.message': 'Cuéntanos sobre tu proyecto o requisitos...',

    'contact.form.subjects.generalinquiry': 'Consulta General',
    'contact.form.subjects.openbravoconsultation': 'Consulta Openbravo',
    'contact.form.subjects.odooimplementation': 'Implementación Odoo',
    'contact.form.subjects.aisolutions': 'Soluciones de IA',
    'contact.form.subjects.customdevelopment': 'Desarrollo Personalizado',
    'contact.form.subjects.technicalsupport': 'Soporte Técnico',
    'contact.form.subjects.partnershipopportunity': 'Oportunidad de Asociación',
    'contact.form.subjects.other': 'Otro',

    'contact.info.title': 'Ponte en Contacto',
    'contact.info.email': 'Email',
    'contact.info.emailDesc': 'Envíanos un email en cualquier momento',
    'contact.info.phone': 'Teléfono',
    'contact.info.phoneDesc': 'Llámanos durante horario comercial',
    'contact.info.office': 'Ubicaciones de Oficina',
    'contact.info.officeDesc': 'Visítanos en nuestras oficinas',
    'contact.info.hours': 'Horario Comercial',
    'contact.info.hoursDesc': '9:00 AM - 6:00 PM (GMT)',

    'contact.whyContact.title': '¿Por qué contactarnos?',
    'contact.whyContact.item1': 'Consulta inicial gratuita y evaluación del proyecto',
    'contact.whyContact.item2': 'Soluciones personalizadas adaptadas a tus necesidades específicas',
    'contact.whyContact.item3': 'Equipo experto con historial comprobado en soluciones empresariales',
    'contact.whyContact.item4': 'Soporte continuo y mantenimiento para todas nuestras implementaciones',

    // Footer
    'footer.description': 'Transformando empresas a través de soluciones tecnológicas innovadoras y servicios de consultoría experta.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Servicios',
    'footer.contactInfo': 'Información de Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.legal': 'Aviso Legal',
    'footer.sitemap': 'Mapa del Sitio',

    // ChatBot
    'chatbot.title': 'Asistente Doce Leguas',
    'chatbot.subtitle': '¿Cómo podemos ayudarte hoy?',
    'chatbot.welcome': '¡Hola! Estoy aquí para ayudarte a conocer más sobre nuestros servicios y soluciones. ¿Cómo puedo asistirte hoy?',
    'chatbot.placeholder': 'Escribe tu mensaje...',
    'chatbot.open': 'Abrir chat',
    'chatbot.close': 'Cerrar chat',
    'chatbot.defaultResponse': 'Gracias por tu mensaje. Nuestro equipo te responderá pronto con más información.',
    'chatbot.errorMessage': 'Lo siento, tengo problemas de conexión ahora. Por favor intenta más tarde o contáctanos directamente.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language] || translations['en'];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};